
MUSIC.event.getWheelDelta=function(event){if(event.wheelDelta){return event.wheelDelta;}else{return-event.detail*40;}};MUSIC.scrollbar=(function(){var E=MUSIC.event;var D=MUSIC.dom;var bar,barp,cont,contp,barsz,barpsz,contsz,contpsz,rate,i=0,bmax,isScroll=false,intf,delta,bnewy,cnewy,barclassname,_options={bartop:"",barleft:0,bar_hover:"",wheel_len:8,wheel_num:15,interval:10};function init(options){bar=D.get(options.barid);cont=D.get(options.contid);barp=bar.parentNode;barp.style.display="";contp=cont.parentNode;contsz=D.getSize(cont);barpsz=D.getSize(barp);contpsz=D.getSize(contp);barclassname=bar.className;ullen=D.getSize(D.get(options.ulid))[1];var rate1=ullen/barpsz[1];var newheight=parseInt(barpsz[1]/rate1);_options.barleft=D.getStyle(bar,"left");if(_options.bartop===""){_options.bartop=parseInt(D.getStyle(bar,"top"));}else{D.setXY(cont,0,0);D.setXY(bar,_options.barleft,_options.top);}
_options.bar_hover=barclassname;MUSIC.object.extend(_options,options||{});if(newheight<20){newheight=20;}
if(newheight>barpsz[1]-_options.bartop*2){bar.style.display="none";barp.style.display="none";E.removeEvent(bar,"mousedown",setBar);E.removeEvent(barp,"click",setBarp,arr);(function(){E.removeEvent(contp,"mousewheel",setWheel);E.removeEvent(contp,"DOMMouseScroll",setWheel);})();if(isScroll){clearInterval(intf);isScroll=false;}
return;}
bar.style.height=newheight+"px";bar.style.display="none";bar.style.display="";barsz=D.getSize(bar);if(isScroll){clearInterval(intf);isScroll=false;}
rate=(ullen-contpsz[1])/(barpsz[1]-barsz[1]-_options.bartop);bmax=barpsz[1]-barsz[1]-2*_options.bartop-1;cmax=contsz[1]-contpsz[1];E.addEvent(bar,"mousedown",setBar);var body=document.body;E.addEvent(body,"mouseup",function(){E.removeEvent(body,"mousemove",showchange);bar.className=barclassname;});var arr={"top":parseInt(D.getStyle(bar,"top")),"ey":D.getXY(bar)[1]+barsz[1]/2};E.addEvent(barp,"click",setBarp,arr);(function(){E.addEvent(contp,"mousewheel",setWheel);E.addEvent(contp,"DOMMouseScroll",setWheel);})();}
function setBarp(e,arr){var target=E.getTarget(e);if(target==this){showchange(e,arr);}}
function showchange(e,arr){var event=E.getEvent(e);E.preventDefault(e);var y=E.mouseY(event);var moveY=y-arr.ey;var newy=moveY+arr.top;var cnewy=-newy*rate;if(newy<=_options.bartop){newy=_options.bartop;cnewy=0;}else if(newy>bmax){newy=bmax;cnewy=-cmax;}
if(cnewy+cmax<0){cnewy=-cmax;}
D.setXY(cont,0,cnewy);D.setXY(bar,_options.barleft,newy);}
function setBar(e){var event=E.getEvent(e);E.preventDefault(event);var barxy=D.getXY(bar);var ey=E.mouseY(event);var top=barxy[1]-D.getXY(barp)[1];var arr={"top":top,"ey":ey};E.addEvent(document.body,"mousemove",showchange,arr);bar.className=_options.bar_hover;}
function changewheel(){if(delta+1){i++;}else{i--;}
if(i==0){clearInterval(intf);isScroll=false;}
bnewy+=-delta*_options.wheel_len/rate;cnewy+=delta*_options.wheel_len;if(bnewy<_options.bartop){bnewy=_options.bartop;i==0;}else if(bnewy>bmax){bnewy=bmax;i==0;}
if(cnewy>0){cnewy=0;}else if(cmax+cnewy<0){cnewy=-cmax;}
D.setXY(cont,0,cnewy);D.setXY(bar,_options.barleft,bnewy);}
function setWheel(e){var event=E.getEvent(e);E.preventDefault(event);delta=E.getWheelDelta(event)/120;if(!isScroll){isScroll=true;bnewy=D.getXY(bar)[1]-D.getXY(barp)[1];cnewy=D.getXY(cont)[1]-D.getXY(contp)[1];if(delta+1){i=-_options.wheel_num;}else{i=_options.wheel_num;}
intf=setInterval(changewheel,_options.interval);}else{if(delta+1){if(i<0){i=i-_options.wheel_num;}else{i=-_options.wheel_num;}}else{if(i<0){i=_options.wheel_num;}else{i=i+_options.wheel_num;}}}}
function selectElement(element){if(bar.style.display=="none"){return;}else{var element=D.get(element);var position=D.getXY(element);var contParentXY=D.getXY(contp);var cnewy=position[1]-contParentXY[1];var bnewy=cnewy/rate;if(bnewy<=_options.bartop+10){bnewy=_options.bartop;cnewy=0;}else if(bnewy>bmax){bnewy=bmax;cnewy=cmax;}
if(cnewy>cmax){cnewy=cmax;}else if(cnewy<0){cnewy=0;}
D.setXY(cont,0,-cnewy);D.setXY(bar,_options.barleft,bnewy);}}
return{init:init,selectElement:selectElement};})();MUSIC.moveTilte=(function(){var D=MUSIC.dom,E=MUSIC.event,title,box,intf=0,timeoutf=0,setOver=false,currenty=0,titley=0;function init(titleId){title=document.getElementById(titleId);box=title.parentNode;titley=D.getSize(title)[1];E.addEvent(box,"mouseout",mouseout);E.addEvent(box,"mouseover",mouseover);}
function mouseout(event){var e=E.getEvent(event);var target=E.getTarget(e);var relativeElement=E.getRelatedTarget(e);if(!D.isAncestor(box,relativeElement)){clearTimeout(timeoutf);timeoutf=setTimeout(function(){intf=setInterval(function(){if(currenty<titley){var changey=Math.ceil((titley-currenty)/4);currenty=currenty+changey;D.setXY(title,0,-currenty);}else{clearInterval(intf);}},50);},3000);}}
function mouseover(event){var e=E.getEvent(event);var target=E.getTarget(e);var relativeElement=E.getRelatedTarget(e);if(!D.isAncestor(box,relativeElement)){if(!setOver){clearTimeout(timeoutf);clearInterval(intf);setOver=true;intf=setInterval(function(){if(currenty>0){var changey=Math.ceil(currenty/4);currenty=currenty-changey;D.setXY(title,0,-currenty);}else{clearInterval(intf);setOver=false;}},50);}}}
function recover(){clearTimeout(timeoutf);clearInterval(intf);intf=setInterval(function(){if(currenty>0){var changey=Math.ceil(currenty/4);currenty=currenty-changey;D.setXY(title,0,-currenty);}else{clearInterval(intf);setOver=false;}},50);timeoutf=setTimeout(function(){intf=setInterval(function(){if(currenty<titley){var changey=Math.ceil((titley-currenty)/4);currenty=currenty+changey;D.setXY(title,0,-currenty);}else{clearInterval(intf);}},50);},3000);}
return{init:init,recover:recover};})();MUSIC.pic=(function(){var mun1=100,mun2=100,intf1=null,temp=null,intf2=null,outf=null;var img1=document.getElementById('img1');var img2=document.getElementById('img2');function change(src){clearTimeout(outf);if(intf1||intf2){clearInterval(intf1);clearInterval(intf2);intf1=intf2=null;img1.style.filter='alpha(opacity=0)';img1.style.opacity=0;img2.style.filter='alpha(opacity=0)';img2.style.opacity=0;mun1=0;mun2=100;}
temp=img1;img1=img2;img2=temp;temp=null;outf=setTimeout(function(){img2.onload=function(){img2.style.filter='alpha(opacity=0)';img2.style.opacity=0;img2.style.display="";clearInterval(intf2);intf2=setInterval(function(){if(mun2>0){img2.style.filter='alpha(opacity='+(101-mun2)+')';img2.style.opacity=(101-mun2)/100;mun2-=2;}else{clearInterval(intf2);mun2=100;intf2=null;}},5);}
img2.style.display="none";img2.src=src;},0);clearInterval(intf1);intf1=setInterval(function(){if(mun1>0){img1.style.filter='alpha(opacity='+(mun1)+')';img1.style.opacity=mun1/100;mun1-=2;}else{clearInterval(intf1);intf1=null;mun1=100;}},5);}
return{change:change};})();MUSIC.module.share=(function(){var qzoneShareUrl='http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=%(url)&desc=%(desc)&summary=%(summary)&title=%(title)&pics=%(pics)',pengyouShareUrl='http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?to=pengyou&url=%(url)&desc=%(desc)&summary=%(summary)&title=%(title)&pics=%(pics)',weiboShareUrl='http://v.t.qq.com/share/share.php?url=%(url)&title=%(title)&pic=%(pic)',sinaShareUrl='http://service.weibo.com/share/share.php?url=%(url)&title=%(title)',kaixinShareUrl='http://www.kaixin001.com/repaste/share.php?rurl=%(url)&rcontent=%(desc)&rtitle=%(title)',renrenShareUrl='http://share.renren.com/share/buttonshare.do?link=%(url)&title=%(title)',doubanShareUrl='http://www.douban.com/recommend/?url=%(url)&title=%(title)',sohuShareUrl='http://t.sohu.com/third/post.jsp?content=utf-8&url=%(url)&title=%(title)',netEasyShareUrl='http://t.163.com/article/user/checkLogin.do?link=%(url)&info=%(info)&source=%(source)';_options={url:gLocation,desc:'',summary:'',title:'',pics:'',pic:''};function reset(){_options={url:gLocation,desc:'',summary:'',title:'',pics:'',pic:''};}
function setParam(options){MUSIC.object.extend(_options,options||{});for(var i in _options){_options[i]=encodeURIComponent(_options[i]);}}
function shareToQzone(options){setParam(options);var url=qzoneShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToPengyou(options){setParam(options);var url=pengyouShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToWeibo(options){setParam(options);var url=weiboShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToSina(options){setParam(options);var url=sinaShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToKaixin(options){setParam(options);var url=kaixinShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToRenren(options){setParam(options);var url=renrenShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToDouban(options){setParam(options);var url=doubanShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareToSohu(options){setParam(options);var url=sohuShareUrl.jstpl_format(_options);window.open(url);reset();}
function shareTo163(options){setParam(options);var url=netEasyShareUrl.jstpl_format({url:_options.url,info:_options.desc+_options.url,source:encodeURIComponent('QQ����')});window.open(url);reset();}
return{shareToQzone:shareToQzone,shareToWeibo:shareToWeibo,shareToPengyou:shareToPengyou,shareToSina:shareToSina,shareToKaixin:shareToKaixin,shareToRenren:shareToRenren,shareToSohu:shareToSohu,shareTo163:shareTo163,shareToDouban:shareToDouban};})();var g_share=MUSIC.module.share;MUSIC.channel.fm={isQplus:window.location.href.indexOf('app_id=200002266')>-1?1:0,isPengyou:window.location.href.indexOf('pengyou')>-1?1:0,_song_num:10,_sim_song_num:5,_type_num:3,_callback_counter:0,_callback_timer:null,_curFmInfo:{fmType:0,fmId:0,fmName:""},_fmInfoObj:{},_fmNameObj:{},_fmListInfo:{},_curSongInfo:null,_isPlayNow:true,_isLoading:false,_divSongCover:null,_divSongName:null,_divSongTime:null,_divSongBar:null,_btnPlay:null,_btnLike:null,_curChn:null,_chnContainer:{},_curChnType:null,_curChnList:null,_myFavFm:null,_myFavSong:null,_isFirstInit:true,_statArrNum:7,_statArr:['','','','','','',''],_curSongList:null,_nextSongInfo:null,_isAddNextSong:false,_isShowNextSong:false,_isFirstPlay:true,init:function(options){if(!!options&&!!options.fmInfoObj){MUSIC.object.extend(this._fmInfoObj,options.fmInfoObj||{});}
var $D=MUSIC.dom;this._divSongCover=$D.get("divsongcover");this._divSongName=$D.get("divsongname");this._divSongTime=$D.get("divsongtime");this._divSongBar=$D.get("divsongbar");this._btnPlay=$D.get("btnplay");this._btnLike=$D.get("btnlike");this._myFavFm=$D.get("divmyfavfm");this._myFavSong=$D.get("divmyfavsong");this._songRecord=$D.get("divsongrecord");this._curChnType=$D.get("ch_1");this._curChnList=$D.get("content_1");MUSIC.moveTilte.init("player_title");this.renderFmList();this.showUserInfo();this.selectFmEvent();if(!g_fmChn.isQplus&&!g_fmChn.isPengyou){$D.get('footer').style.display='block';}
g_musicMain.init();$.qPlayer.init({fromtag:29,statFromtag:5});g_fmChn.listenrecord.report();g_fmChn.keeplogin.keep();$.qPlayer.on("playbegin",function(playInfo){var songinfo=playInfo.songInfo,index=playInfo.index,total=playInfo.total;g_fmChn.updateCurSong(songinfo);g_fmChn._divSongTime.innerHTML='';if(g_fmChn.myFavSong.isInSongList(songinfo.mid)){g_fmChn._btnLike.onclick=g_fmChn.delSong;g_fmChn._btnLike.className="btn_like_on";g_fmChn._btnLike.title="取消喜欢";}else{g_fmChn._btnLike.onclick=g_fmChn.likeSong;g_fmChn._btnLike.className="btn_like";g_fmChn._btnLike.title="喜欢";}
if(g_fmChn._curFmInfo.fmType!=100){hideElement('song_reason');}
g_fmChn._isShowNextSong=false;if(index>=total-1){g_fmChn._isPlayNow=false;hideElement('song_reason');g_fmChn._isShowNextSong=true;g_fmChn.playFm(g_fmChn._curFmInfo);}else{if(g_fmChn._curFmInfo.fmType==100){g_fmChn._nextSongInfo=g_fmChn._curSongList[index+1];g_fmChn.showNextSongInfo();}}
if(g_fmChn.isShowLrc(g_fmChn._curFmInfo.fmId,g_fmChn._curFmInfo.fmType)){MUSIC.dom.get('song_lrc').innerHTML='<p>&nbsp;</p><p>歌词正在加载中...</p>';g_qrcHandlerChn.clearQrcInfo();g_qrcHandlerChn.init({songId:songinfo.mid,qrcContainer:'song_lrc'});g_lrcHandlerChn.clearLrcInfo();}else{MUSIC.dom.get('song_lrc').innerHTML='<p>&nbsp;</p><p><a href="javascript:;" style="cursor:default;text-decoration: none;">纯音乐不提供歌词</a></p>';g_qrcHandlerChn.clearQrcInfo();g_lrcHandlerChn.clearLrcInfo();}
if(g_fmChn._isFirstPlay){g_fmChn._isFirstPlay=false;}});$.qPlayer.on("playend",function(playInfo){var songinfo=playInfo.songInfo;if(g_fmChn._statArr[0]!=''){if((new Date().valueOf())%100==0){g_stat2(g_fmChn._statArr);}
for(var i=0;i<g_fmChn._statArrNum;i++){g_fmChn._statArr[i]='';}}
var pt=g_fmChn.playtime.get();if(songinfo.mid!=0){g_fmChn.listenrecord.add({songid:songinfo.mid,playtime:pt+'',source:'9',actionid:'2'});if(g_fmChn._curFmInfo.fmType==100){g_fmChn.simrecord.add({songid:songinfo.mid,actionid:'2',playtime:pt+'',source:'9'});}}
if(typeof songinfo.minterval!='undefined'){if(songinfo.minterval-pt<3){g_fmChn.songRecord.addSongId(songinfo.mid,function(num){g_fmChn.updateSongRecordNum(num);});}}
g_fmChn.fm_stat(1,pt);g_fmChn.playtime.end();if(g_qrcHandlerChn.haveqrc){g_qrcHandlerChn.clearQrcInfo();}else if(g_lrcHandlerChn.haveLrc){g_lrcHandlerChn.clearLrcInfo();}});$.qPlayer.on("playing",function(){g_fmChn._btnPlay.className="btn_pause";g_fmChn._btnPlay.innerHTML="暂停";g_fmChn._btnPlay.title="暂停";g_fmChn._btnPlay.onclick=g_fmChn.pauseFm;if(g_fmChn._isFirstInit){g_storage.get('fmvol',function(vol){vol=vol||'75';g_fmChn.initVol(vol);$.qPlayer.volume(vol);});g_fmChn._isFirstInit=false;}else{g_fmChn.initVol(Math.round($.qPlayer.volume()));}});$.qPlayer.on("pause",function(){g_fmChn._btnPlay.className="btn_play";g_fmChn._btnPlay.innerHTML="播放";g_fmChn._btnPlay.title="播放";g_fmChn._btnPlay.onclick=g_fmChn.startFm;});$.qPlayer.on("timeupdate",function(timeinfo){g_fmChn.updateSongBar(timeinfo.currentTime,timeinfo.totalTime);});},myFavFm:{idList:[],currentPage:1,itemNum:10,maxPage:1,isLoad:false,init:function(json){this.idList=MUSIC.lang.objectClone(json).radio_list.reverse();for(var i=0;i<this.idList.length;i++){if(!g_fmChn._fmNameObj[this.idList[i].radioid+'_'+this.idList[i].type]){this.idList.splice(i,1);i--;}}
this.maxPage=Math.ceil(this.idList.length/this.itemNum);if(this.maxPage==0){this.maxPage=1;}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);},getList:function(){var _this=this;g_fmChn.favFm.getList(function(json){_this.isLoad=true;_this.init(json);g_fmChn._callback_counter++;});},showPage:function(pageNum){if(pageNum>this.maxPage||pageNum<1){}else{this.currentPage=pageNum;var i=(pageNum-1)*this.itemNum,len=pageNum*this.itemNum,maxIndex=this.idList.length,listHTML=[],itemHTML="",item,radioNameList=g_fmChn._fmNameObj;for(;i<len;i++){if(i<maxIndex){item=this.idList[i];itemHTML='<li onmouseover="this.className=\'on\';" onmouseout="this.className=\'\';"><span class="radio">'+radioNameList[item.radioid+'_'+item.type]+'</span><span class="play"><a href="#'+item.radioid+'_'+item.type+'" class="icon_play" title="播放" onclick="g_fmChn.setChnAndList('+item.radioid+','+item.type+');g_dialog.hide();">播放</a></span><span class="del"><a href="javascript:;" onclick="g_fmChn.myFavFm.deleteItem('+i+');" class="icon_del" title="取消">取消</a></span></li>';listHTML.push(itemHTML);}else{break;}}
var k=1,navHTML=[],navLi='';navHTML.push('<span class="num">');for(;k<=this.maxPage;k++){if(k!=pageNum){navLi='<a href="javascript:;" onclick="g_fmChn.myFavFm.showPage('+k+')">'+k+'</a>';}else{navLi='<a href="javascript:;" class="on">'+k+'</a>';}
navHTML.push(navLi);}
navHTML.push('</span>');if(pageNum<this.maxPage){navHTML.push('<a href="javascript:;" onclick="g_fmChn.myFavFm.nextPage()">下一页</a>');}
if(pageNum>1){navHTML.unshift('<a href="javascript:;" onclick="g_fmChn.myFavFm.prevPage()">上一页</a>');}
if(this.idList.length==0){listHTML.push('<div class="radioisnull"><p>你还没有收藏任何电台。</p></div>');navHTML=[];}
if(this.maxPage==1){navHTML=[];}
var doc=document;doc.getElementById("myFavFmPage").innerHTML=listHTML.join("");doc.getElementById("myFavFmNav").innerHTML=navHTML.join("");}},nextPage:function(){if(this.currentPage<this.maxPage){this.showPage(++this.currentPage);}},prevPage:function(){if(this.currentPage>1){this.showPage(--this.currentPage);}},addToMyFavFmList:function(info){var info=info,_this=this;g_fmChn.favFm.add({'fmId':info.radioid,'fmType':info.type},function(){_this.idList.unshift(info);_this.maxPage=Math.ceil(_this.idList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}});},deleteFromMyFavFmList:function(info){var index=-1;for(var i=0,len=this.idList.length;i<len;i++){if(this.idList[i].radioid==info.radioid){index=i;break;}}
if(index>=0){var info=info,_this=this;g_fmChn.favFm.del({'fmId':info.radioid,'fmType':info.type},function(){var deletFM=_this.idList.splice(index,1);_this.maxPage=Math.ceil(_this.idList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}});}},deleting:0,deleteItem:function(index){if(g_fmChn.favFm.deleting){return;}
g_fmChn.favFm.deleting=1;var index=index,deletFM=this.idList[index],_this=this;g_fmChn.favFm.del({'fmId':deletFM.radioid,'fmType':deletFM.type},function(){var deletFM=_this.idList.splice(index,1);_this.maxPage=Math.ceil(_this.idList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}
if(_this.currentPage<=_this.maxPage){_this.showPage(_this.currentPage);}else{_this.prevPage();}
g_fmChn.favFm.deleting=0;});},show:function(){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
var myFavFmHTML=('<div class="radiolist"><ul id="myFavFmPage"></ul></div><div class="pager" id="myFavFmNav"></div>');if(!this.isLoad){var _this=this;g_fmChn.favFm.getList(function(data){_this.isLoad=true;_this.init(data);g_dialog.show({mode:"bigpage",title:"我收藏的电台",desc:myFavFmHTML,width:400,isLoadCss:false});_this.showPage(1);});}else{g_dialog.show({mode:"bigpage",title:"我收藏的电台",desc:myFavFmHTML,width:400,isLoadCss:false});this.showPage(1);}}},myFavSong:{songList:[],songListMap:[],currentPage:1,itemNum:10,maxPage:1,isLoad:false,init:function(json){this.songList=MUSIC.lang.objectClone(json).SongList;for(var i=0,len=this.songList.length;i<len;i++){this.songListMap[this.songList[i].id]=true;}
this.maxPage=Math.ceil(this.songList.length/this.itemNum);if(this.maxPage==0){this.maxPage=1;}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);},getList:function(){var _this=this;g_fmChn.favSong.getList(function(json){_this.init(json);g_fmChn._callback_counter++;});},isInSongList:function(songId){return!!this.songListMap[songId];},addToMyFavSongList:function(songInfo){var _this=this,songInfo=songInfo;g_fmChn.favSong.add(songInfo.id,songInfo.type,function(){_this.songList.unshift(songInfo);_this.songListMap[songInfo.id]=true;_this.maxPage=Math.ceil(_this.songList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}});},delFromFavSongList:function(songId,songType){var id=songId,type=songType||3,_this=this;g_fmChn.favSong.del(songId,songType,function(){_this.songListMap[id]=false;for(var i=0;i<_this.songList.length;i++){if(_this.songList[i].id==id){_this.songList.splice(i,1);_this.maxPage=Math.ceil(_this.songList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}
break;}}});},showPage:function(pageNum){if(pageNum>this.maxPage||pageNum<1){}else{this.currentPage=pageNum;var i=(pageNum-1)*this.itemNum,len=pageNum*this.itemNum,listHTML=[],itemHTML="",item,maxIndex=this.songList.length;for(;i<len;i++){if(i<maxIndex){var item=this.songList[i];itemHTML='<li onmouseover="this.className=\'on\';" onmouseout="this.className=\'\';"><span class="songname">'+item.songname+'</span><span class="artists">'+item.singername+'</span><span class="album">'+item.diskname+'</span><span class="del"><a href="javascript:;" class="icon_del" title="取消" onclick="g_fmChn.myFavSong.deleteItem('+i+')">取消</a></span></li>';listHTML.push(itemHTML);}else{break;}}
var k=1,navHTML=[],navLi='',navList=[];navHTML.push('<span class="num">');for(;k<=this.maxPage;k++){if(k!=pageNum){navLi='<a href="javascript:;" onclick="g_fmChn.myFavSong.showPage('+k+')">'+k+'</a>';}else{navLi='<a href="javascript:;"  class="on">'+k+'</a>';}
navList.push(navLi);}
if(this.maxPage<=13){}else{if(this.currentPage>7){navList.splice(1,this.currentPage-7,"...");if(this.maxPage-this.currentPage>6){navList.splice(13,this.maxPage-6-this.currentPage,"...");}}else{if(this.maxPage-this.currentPage>6){navList.splice(this.currentPage+5,this.maxPage-6-this.currentPage,"...");}}}
navHTML.push(navList.join(""));navHTML.push('</span>');if(pageNum<this.maxPage){navHTML.push('<a href="javascript:;" onclick="g_fmChn.myFavSong.nextPage()">下一页</a>');}
if(pageNum>1){navHTML.unshift('<a href="javascript:;" onclick="g_fmChn.myFavSong.prevPage()">上一页</a>');}
var doc=document;if(this.songList.length==0){listHTML=[];navHTML=[];doc.getElementById("play_all").style.display="none";doc.getElementById("songnullpage").style.display="";doc.getElementById("myFavSongPage").parentNode.style.display="none";doc.getElementById("myFavSongNav").style.display="none";doc.getElementById("cont_head").style.display="none";}else{doc.getElementById("play_all").style.display="";doc.getElementById("songnullpage").style.display="none";doc.getElementById("cont_head").style.display="";doc.getElementById("myFavSongPage").parentNode.style.display="";doc.getElementById("myFavSongNav").style.display="";}
if(this.maxPage==1){navHTML=[];}
doc.getElementById("myFavSongPage").innerHTML=listHTML.join("");doc.getElementById("myFavSongNav").innerHTML=navHTML.join("");}},nextPage:function(){if(this.currentPage<this.maxPage){this.showPage(++this.currentPage);}},prevPage:function(){if(this.currentPage>1){this.showPage(--this.currentPage);}},deleteItem:function(index){var deleteItem=this.songList[index],_this=this;g_fmChn.favSong.del(deleteItem.id,deleteItem.type,function(){_this.songListMap[deleteItem.id]=false;for(var i=0;i<_this.songList.length;i++){if(_this.songList[i].id==deleteItem.id){_this.songList.splice(i,1);break;}}
_this.maxPage=Math.ceil(_this.songList.length/_this.itemNum);if(_this.maxPage==0){_this.maxPage=1;}
if(_this.currentPage<=_this.maxPage){_this.showPage(_this.currentPage);}else{_this.prevPage(_this.currentPage);}});},show:function(){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
var myFavSongHTML=('<div class="hint" id="cont_head">我喜欢收录您在QQ音乐上标记过喜欢的所有歌曲，并可随时随地在任何联网设备上访问。</div><div class="songlist"><ul id="myFavSongPage"></ul></div><div class="pager" id="myFavSongNav"></div><div class="songisnull" id="songnullpage" style="display:none;padding-left:20px;"><p>您还没有对任何歌曲标记过喜欢。</p><p>轻轻点击歌曲后的喜欢按钮，就可以将歌曲快速收藏到我喜欢列表。</p><p>而且QQ音乐可以永远记住你的喜好，给你推荐越来越符合你口味的歌曲。</p><p>快来体验吧！</p>');g_dialog.show({mode:"bigpage",title:'<span>我喜欢</span><a href="javascript:;" onclick="g_fmChn.myFavSong.playAll();g_fmChn.fm_stat(10)" class="icon_playall" id="play_all" >全部播放</a>',desc:myFavSongHTML,width:600,isLoadCss:false});this.showPage(1);},isAddSosoPlaylist:false,addSoSoPlaylist:function(aList,oPostData){var url="http://qzone-music.qq.com/fcg-bin/fcg_soso_addsong.fcg";var data={formsender:1,uin:g_user.getUin()>1000?g_user.getUin():34567890,songlist:this.getPostData(aList),utf8:1};var fs=new MUSIC.FormSender(url,"post",data,"utf-8");fs.onSuccess=function(o){if(!o||typeof(o)!="object"){}
else
{switch(parseInt(o.code)){case 0:{oPostData.k=o.key;break;}
default:{break;}}}
g_fmChn.myFavSong.OpenPostWindow("http://qzone-music.qq.com/fcg-bin/yqqcom_play_mid.fcg","_webQQMusicPlayer",oPostData);g_fmChn.myFavSong.isAddSosoPlaylist=false;};fs.onError=function(){g_fmChn.myFavSong.OpenPostWindow("http://qzone-music.qq.com/fcg-bin/yqqcom_play_mid.fcg","_webQQMusicPlayer",oPostData);g_fmChn.myFavSong.isAddSosoPlaylist=false;};if(!g_fmChn.myFavSong.isAddSosoPlaylist)
{g_fmChn.myFavSong.isAddSosoPlaylist=true;fs.send();}},playAll:function(){if(this.songList.length>0){var songinfo_list=[],begain=(this.currentPage-1)*this.itemNum,end=this.currentPage*this.itemNum,maxIndex=this.songList.length,tmp;for(;begain<end;begain++){if(begain<maxIndex){tmp=this.songList[begain];songinfo_list.push([tmp.id,tmp.type,tmp.url,tmp.songname,tmp.singerid,tmp.singername,tmp.diskid,tmp.diskname,tmp.playtime]);}else{break;}}
if(songinfo_list.length>0){this.openEmptyWindow("_webQQMusicPlayer");this.addSoSoPlaylist(songinfo_list,{songList:'',type:1,vip:-1,userName:'',playXsosoFlag:0,source:9,u:g_user.getUin()>1000?g_user.getUin():34567890,k:0});}else{return;}}},openEmptyWindow:function(sWindowName)
{if(typeof sWindowName!=="string"){sWindowName="_webQQMusicPlayer";}
try{if(!ua.ie)
{if(top.window.win)
{top.window.win.close();top.window.win=null;}}}
catch(e)
{}
try{if(!top.window.win||top.window.win.closed==true)
{top.window.win=window.open("",sWindowName);if(!top.window.win&&!(ua.tt>=5))
{MUSIC.showMsgbox("弹出窗口被拦截,请取消拦截!",1,2000);}}}
catch(e)
{}},OpenPostWindow:function(sUrl,sWindowName,oPostData){if(typeof sWindowName!=="string"){sWindowName="";}
var sFormId="post_window_form";var oForm=document.getElementById(sFormId);if(oForm!=null){document.body.removeChild(oForm);}
var oForm=document.createElement("form");oForm.id=sFormId;oForm.action=sUrl;oForm.method="POST";oForm.target=sWindowName;for(key in oPostData){var oInput=document.createElement("input");oInput.type="hidden";oInput.name=key;oInput.value=oPostData[key];oForm.appendChild(oInput);}
document.body.appendChild(oForm);oForm.submit();},getPostData:function(aList){var iLen=aList.length;if(iLen===0){return"[];";}
var sJson="[";for(var i=0;i<iLen;i++){if(i>0){sJson+=',';}
var iLen2=aList[i].length;if(iLen2==0){sJson+='[]';continue;}
sJson+='[';for(var j=0;j<iLen2;j++){if(j>0){sJson+=',';}
sJson+='"'+(aList[i][j]).toString().replace(/"/g,'\\"')
+'"';}
sJson+=']';}
sJson+="]";return sJson;}},updateMyFavNum:function(fmNum,songNum){g_fmChn._myFavFm.innerHTML='我收藏的电台('+fmNum+')';g_fmChn._myFavSong.innerHTML='我喜欢('+songNum+')';},updateSongRecordNum:function(songRecordNum){g_fmChn._songRecord.innerHTML='我听过的歌('+songRecordNum+')';},renderFmList:function(){var list_tpl1='<li><a href="#%(id)_%(type)" hidefocus="hidefocus" title="%(name)"><span><strong>%(name)</strong><em>MHz</em></span></a></li>';var list_tpl2='<li><a href="#%(id)_%(type)" hidefocus="hidefocus" title="%(name)"><span><strong>%(name)</strong></span></a></li>';var type=1,id=0;var fmInfo={};var location=window.location.href;var reg=/#\d+_\d+/g,res=location.match(reg);if(res){var hrefparts=res[0].substring(1);hrefparts=hrefparts.split('_');id=hrefparts[0];type=hrefparts[1];}
var inited=true;var fm={};for(var j=1;j<=this._type_num;j++){var list=this._fmInfoObj["type"+j];for(var i=0,len=list.length;i<len;i++){list[i].type=j;this._fmNameObj[list[i].id+"_"+j]=list[i].name;this._fmListInfo[list[i].id+"_"+j]=list[i].i;if(!fm[list[i].i]){fm[list[i].i]=[];}
if(j!=2){fm[list[i].i].push(list_tpl1.jstpl_format(list[i]));}else{fm[list[i].i].push(list_tpl2.jstpl_format(list[i]));}
if(inited){fmInfo.fmType=1;fmInfo.fmId=list[i].id;fmInfo.fmName=list[i].name;inited=false;}}}
for(var name in fm){MUSIC.dom.get("content_"+name).innerHTML+=fm[name].join('');}
for(var i=1;i<=this._type_num;i++){if(!MUSIC.dom.get("content_"+i)){continue;}
var node=MUSIC.dom.getFirstChild("content_"+i);if(!node){continue;}
fnode=MUSIC.dom.getFirstChild(node);if(!fnode){continue;}
var _href=fnode.getAttribute("href");_href=_href.substring(_href.indexOf('#'));this._chnContainer[_href]=fnode;while(node=MUSIC.dom.getNextSibling(node)){var fnode=MUSIC.dom.getFirstChild(node);_href=fnode.getAttribute("href");_href=_href.substring(_href.indexOf('#'));this._chnContainer[_href]=fnode;}}
this._chnContainer["#0_100"]=MUSIC.dom.get("ch_0_100");this._fmNameObj["0_100"]="猜你喜欢";var tag='#'+id+'_'+type;if(!!this._chnContainer[tag]){fmInfo.fmType=type;fmInfo.fmId=id;fmInfo.fmName=this._fmNameObj[id+"_"+type];}else{if(type==2){this._curChn={};this.setCurChnType(this._fmListInfo['118_1']);MUSIC.scrollbar.init({barid:"bar",contid:"content",bar_hover:"slider slider_hover",ulid:this._curChnList});this.setCurChnType(this._fmListInfo['118_1']);this.playFm({fmId:id,fmType:type});return;}
var uin=g_user.getUin();if(uin>10000){g_storage.get('fmchannle'+uin,function(record){record=record||'';if(record!=''&&!!g_fmChn._chnContainer['#'+record]){var arr=record.split('_');fmInfo.fmId=arr[0];fmInfo.fmType=arr[1];fmInfo.fmName=g_fmChn._fmNameObj[fmInfo.fmId+"_"+fmInfo.fmType];}});}}
this._curChn=this._chnContainer['#'+fmInfo.fmId+'_'+fmInfo.fmType];this.setChnAndList(fmInfo.fmId,fmInfo.fmType);MUSIC.scrollbar.init({barid:"bar",contid:"content",bar_hover:"slider slider_hover",ulid:this._curChnList});this.setChnAndList(fmInfo.fmId,fmInfo.fmType);},showUserInfo:function(){if(!g_user.isLogin()){return;}
g_user.getVipInfo(function(data){if(data.vip!=1&&data.vip!=2){return;}
var elem=MUSIC.dom.get("divuserinfo");if(elem){elem.innerHTML=(data.nickname!=""?data.nickname:g_user.getUin())+((g_fmChn.isQplus||g_fmChn.isPengyou)?'':'<a href="javascript:;" onclick="g_user.loginOut(g_fmChn.fm_logout);">[退出]</a>');}
g_fmChn.myFavFm.getList();g_fmChn.myFavSong.getList();g_fmChn.songRecord.getNum(function(num){g_fmChn.updateSongRecordNum(num);});g_fmChn._callback_counter++;});},shareFm:function(){var share_url=window.location.href.replace(/\?app_id=200002266/g,'').replace(/\/pengyou/g,'');g_share.shareToWeibo({url:share_url,desc:'',summary:'',title:'#QQ音乐电台'+g_fmChn._curFmInfo.fmName+'频道#',pic:'http://qzonestyle.gtimg.cn/music/photo/album_300/'+(g_fmChn._curSongInfo.malbumid%100)+'/300_albumpic_'+g_fmChn._curSongInfo.malbumid+'_0.jpg'});g_fmChn.fm_stat(6);},addFavFm:function(){g_fmChn.myFavFm.addToMyFavFmList({radioid:g_fmChn._curFmInfo.fmId,type:g_fmChn._curFmInfo.fmType});g_fmChn.fm_stat(7);},goMyFavFmList:function(){g_fmChn.myFavFm.show();},goMyFavSongList:function(){g_fmChn.myFavSong.show();g_fmChn.fm_stat(9);},getSimSongList:function(history_list,callback){var uin=g_user.getUin(),url="",cbname="SongRecCallback";url="http://s.plcloud.music.qq.com/fcgi-bin/song_sim.fcg?utf8=1&start=-1&num="+this._sim_song_num+"&uin="+uin+"&history_list="+history_list+"&rnd="+new Date().valueOf();cbname="SongRecCallback";function _error(){g_popup.show(1,"获取电台歌曲信息失败！","当前网络繁忙，请您稍后重试。",1000,320,true,false);g_fmChn._isLoading=false;}
function formatMusic(songdata){var _arrSongAttr=["mid","msong","msingerid","msinger","malbumid","malbum","msize","minterval","mstream","mdownload","msingertype","size320","size128","mrate","gososo","sizeape","sizeflac","sizeogg"];var length=_arrSongAttr.length,arrMusic=songdata.split("|"),_obj={},i=0,_length=Math.min(length,arrMusic.length);for(i=0;i<_length;i++){_obj[_arrSongAttr[i]]=arrMusic[i];}
for(i=_length;i<length;i++){_obj[_arrSongAttr[i]]="";}
return _obj;};var j=new MUSIC.JSONGetter(url,"songlist",null,"utf-8",false);j.onSuccess=function(data){var _songlist=[];if(data.retcode==0){MUSIC.object.each(data.songs,function(info){var _data=formatMusic(unescape(unescape(info.data)).replace(/\+/ig," "));_data.mruleid=100000000;if(typeof data.rule_id!="undefined"){_data.mruleid=data.rule_id;}
if(!!info.desc){_data.desc=info.desc;}else{_data.desc="";}
_data.songurl='http://stream%(stream).qqmusic.qq.com/%(sid).mp3'.jstpl_format({stream:parseInt(_data.mstream,10)+10,sid:parseInt(_data.mid,10)+30000000});_songlist.push(_data);});if(_songlist.length<=0){_error();return;}
if(g_fmChn._isAddNextSong){g_fmChn._isAddNextSong=false;if(!!g_fmChn._nextSongInfo){_songlist.unshift(g_fmChn._nextSongInfo);}}
if(callback){if(g_fmChn._isShowNextSong){g_fmChn._nextSongInfo=_songlist[0];g_fmChn.showNextSongInfo();}
callback(_songlist);}}else if(data.retcode==-2){g_user.callback=(function(history_list,callback){return function(){g_fmChn.getSimSongList(history_list,callback);}})(history_list,callback);g_fmChn.login.open_login();}else{_error();}};j.onError=function(){_error();};j.send(cbname);},getFmSongList:function(fmType,fmId,callback){var uin=g_user.getUin(),url="",cbname="",jsonname="";switch(parseInt(fmType))
{case 1:case 3:url="http://radio.cloud.music.qq.com/fcgi-bin/qm_guessyoulike.fcg?start=-1&num="+this._song_num+"&uin="+uin+"&labelid="+fmId+"&rnd="+new Date().valueOf();cbname="JsonCallBack";jsonname="guessyoulike";break;case 2:url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_singer_radio_client.fcg?start=-1&num="+this._song_num+"&ouin="+uin+"&singerid="+fmId+"&rnd="+new Date().valueOf();cbname="JsonCallBack";jsonname="singerradio";break;case 100:if(uin<10001){g_user.callback=(function(fmType,fmId,callback){return function(){g_fmChn.getFmSongList(fmType,fmId,callback);}})(fmType,fmId,callback);g_fmChn.login.open_login();return;}
g_fmChn.simrecord.getHistoryList(function(history_list){g_fmChn.getSimSongList(history_list,callback);});return;break;default:break;}
function _error(){g_popup.show(1,"获取电台歌曲信息失败！","当前网络繁忙，请您稍后重试。",1000,320,true,false);g_fmChn._isLoading=false;}
function formatMusic(songdata){var _arrSongAttr=["mid","msong","msingerid","msinger","malbumid","malbum","msize","minterval","mstream","mdownload","msingertype","size320","size128","mrate","gososo","sizeape","sizeflac","sizeogg"];var length=_arrSongAttr.length,arrMusic=songdata.split("|"),_obj={},i=0,_length=Math.min(length,arrMusic.length);for(i=0;i<_length;i++){_obj[_arrSongAttr[i]]=arrMusic[i];}
for(i=_length;i<length;i++){_obj[_arrSongAttr[i]]="";}
return _obj;};var j=new MUSIC.JSONGetter(url,jsonname,null,"gb2312",false);j.onSuccess=function(data){var _songlist=[];if(data.retcode==0){MUSIC.object.each(data.songs,function(info){var _data=formatMusic(unescape(unescape(info.data)).replace(/\+/ig," "));_data.mruleid=100000000;if(typeof data.rule_id!="undefined"){_data.mruleid=data.rule_id;}
_data.desc="";_data.songurl='http://stream%(stream).qqmusic.qq.com/%(sid).mp3'.jstpl_format({stream:parseInt(_data.mstream,10)+10,sid:parseInt(_data.mid,10)+30000000});_songlist.push(_data);});if(_songlist.length<=0){_error();return;}
if(callback){if(fmType==2){g_fmChn.updateCurFm({fmId:fmId,fmType:fmType,fmName:_songlist[0].msinger});}
callback(_songlist);}}else if(data.retcode==-2){g_user.callback=(function(fmType,fmId,callback){return function(){g_fmChn.getFmSongList(fmType,fmId,callback);}})(fmType,fmId,callback);g_fmChn.login.open_login();}else{if(data.retcode==7&&fmType==2){g_fmChn.setChnAndList(118,1);return;}
_error();}};j.onError=function(){_error();};j.send(cbname);},updateCurSong:function(songInfo){g_fmChn._curSongInfo=songInfo;if(!g_fmChn.isQplus&&!g_fmChn.isPengyou){document.title=songInfo.msong.unescapeHTML()+' - QQ音乐电台';}
g_fmChn._divSongName.innerHTML=songInfo.msong+' - '+songInfo.msinger;g_fmChn._divSongName.style.width='';if(!!ua.ie&&ua.ie==6){var _slen=MUSIC.dom.getPosition(MUSIC.dom.get(g_fmChn._divSongName)).width;if(_slen>252){g_fmChn._divSongName.style.width='252px';}}
g_fmChn._divSongName.title=songInfo.msong.unescapeHTML()+' - '+songInfo.msinger.unescapeHTML();g_fmChn._divSongTime.innerHTML='';g_fmChn._divSongBar.style.width='0%';MUSIC.pic.change('http://qzonestyle.gtimg.cn/music/photo/album_300/'+(songInfo.malbumid%100)+'/300_albumpic_'+songInfo.malbumid+'_0.jpg');MUSIC.moveTilte.recover();},updateSongBar:function(curtime,totaltime){var $D=MUSIC.dom,$C=MUSIC.css;if(isNaN(curtime)||isNaN(totaltime)){return;}
var cursec=parseInt(curtime,10),totalSec=parseInt(totaltime,10);g_fmChn.playtime.set(cursec,totalSec);function formatTime(seconds){var mins=parseInt(seconds/60,10),secs=parseInt(seconds%60,10);return mins+":"+(secs>9?"":"0")+secs;}
g_fmChn._divSongTime.innerHTML='-'+formatTime(totalSec-cursec);g_fmChn._divSongBar.style.width=parseInt(cursec*100/totalSec,10)+'%';var _h5=(!!ua.safari||!!ua.chrome||!!ua.isiPad||!!ua.isiPhone);var _elem=MUSIC.dom.get('song_lrc');if(!g_fmChn.isShowLrc(g_fmChn._curFmInfo.fmId,g_fmChn._curFmInfo.fmType)){return;}
if(g_qrcHandlerChn.reqFlag){_elem.innerHTML='<p>&nbsp;</p><p>歌词正在加载中...</p>';return;}else{var _innerHtml=(!!_elem&&!!_elem.getElementsByTagName&&_elem.getElementsByTagName('p').length>1)?_elem.getElementsByTagName('p')[1].innerHTML:"";if(g_qrcHandlerChn.haveqrc&&(_innerHtml=="歌词正在加载中..."||_innerHtml=="")){_elem.innerHTML=g_qrcHandlerChn.printQrcLines();g_qrcHandlerChn.startAnimFrame('song_lrc');return;}else if(!g_qrcHandlerChn.haveqrc&&g_lrcHandlerChn.reqFlag==-1){g_lrcHandlerChn.init(g_qrcHandlerChn.playingSong);_elem.innerHTML='<p>&nbsp;</p><p>歌词正在加载中...</p>';return;}else if(!g_qrcHandlerChn.haveqrc&&g_lrcHandlerChn.reqFlag==0){return;}else if(!g_qrcHandlerChn.haveqrc&&g_lrcHandlerChn.reqFlag==1){if(g_lrcHandlerChn.haveLrc&&(_innerHtml=="歌词正在加载中..."||_innerHtml=="")){var _lrcLines=g_lrcHandlerChn.printLrcLines();if(_lrcLines==''){g_lrcHandlerChn.haveLrc=false;_elem.innerHTML='<p>&nbsp;</p><p><a href="http://support.qq.com/write.shtml?fid=602" target="_blank">该单曲暂无歌词，点击这里进行反馈</a></p>';return;}
_elem.innerHTML=_lrcLines;g_lrcHandlerChn.startAnimFrame('song_lrc');return;}else if(!g_lrcHandlerChn.haveLrc){_elem.innerHTML='<p>&nbsp;</p><p><a href="http://support.qq.com/write.shtml?fid=602" target="_blank">该单曲暂无歌词，点击这里进行反馈</a></p>';return;}}}
if(g_qrcHandlerChn.haveqrc){if(g_qrcHandlerChn.getQrcLineItemByPlayTime(curtime*1000)){var _context=g_qrcHandlerChn.lineItem.context,_prePID=(g_qrcHandlerChn.qrcLineIndex-1<0)?'null':g_qrcHandlerChn.qrcLineIndex-1,_pID=g_qrcHandlerChn.qrcLineIndex;var _pNode=$D.get('line_'+_pID);if(!!_pNode){var highlight="";if(_h5){highlight=g_qrcHandlerChn.getHighlightWords(curtime*1000);if(typeof highlight!=="undefined"&&highlight!=""){_pNode.innerHTML=_context.replace(highlight,'<span class="on">'+highlight+'</span>');}}else{highlight='<span class="on">'+_context+'</span>';_pNode.innerHTML=highlight;}
if(_pID>0){var _preNode=$D.get('line_'+_prePID),_preSpan=null;if(!!_preNode){_preSpan=_preNode.getElementsByTagName('span')[0];$C.hasClassName(_preSpan,"on")&&$C.removeClassName(_preSpan,"on");}}}}}else if(g_lrcHandlerChn.haveLrc){if(g_lrcHandlerChn.getLyricLineItemByPlayTime(g_lrcHandlerChn.ms2playTime(curtime*1000))){var _prePID=(g_lrcHandlerChn.preLrcItemIndex==-1)?'null':g_lrcHandlerChn.preLrcItemIndex,_pID=g_lrcHandlerChn.lrcItemIndex;var _pNode=$D.get('line_'+_pID);if(!!_pNode&&_pID!=_prePID){_pNode.innerHTML='<span class="on">'+g_lrcHandlerChn.lrcItem.context+'</span>';if(_pID>0){var _preNode=$D.get('line_'+_prePID),_preSpan=null;if(!!_preNode){_preSpan=_preNode.getElementsByTagName('span')[0];$C.hasClassName(_preSpan,"on")&&$C.removeClassName(_preSpan,"on");}}}}}else{_elem.innerHTML='<p>&nbsp;</p><p><a href="http://support.qq.com/write.shtml?fid=602" target="_blank">该单曲暂无歌词，点击这里进行反馈</a></p>';}},initVol:function(vol){var D=MUSIC.dom,E=MUSIC.event,volumebar=D.get("spanvolumebar"),volumeslider=D.get("spanvolumeslider");volumebar.title="音量："+vol+"%";volumeslider.style.width=vol+"%";},mousedown:function(e){MUSIC.event.cancelBubble(e);MUSIC.event.preventDefault(e);MUSIC.event.addEvent(document.body,"mousemove",g_fmChn.mousemove);MUSIC.event.addEvent(document.body,"mouseup",function(){MUSIC.event.removeEvent(document.body,"mousemove",g_fmChn.mousemove);});},mousemove:function(event){MUSIC.event.cancelBubble(event);MUSIC.event.preventDefault(event);MUSIC.event.addEvent(document.body,"mouseup",function(){MUSIC.event.removeEvent(document.body,"mousemove",g_fmChn.mousemove);});g_fmChn.updateVol();},updateVol:function(){var D=MUSIC.dom,E=MUSIC.event,volumebar=D.get("spanvolumebar"),volumeslider=D.get("spanvolumeslider"),pos=D.getPosition(volumebar),eventx=E.mouseX(),vol=parseInt((eventx-pos["left"])*100/pos["width"],10);if(!isNaN(vol)&&(vol>=0&&vol<101)){volumebar.title="音量："+vol+"%";volumeslider.style.width=vol+"%";$.qPlayer.volume(vol);g_storage.set('fmvol',vol);}},updateCurFm:function(fmInfo){g_fmChn._curFmInfo=fmInfo;MUSIC.dom.get("divfmtitle").innerHTML=fmInfo.fmName;if(typeof g_fmChn._chnContainer['#'+fmInfo.fmId+'_'+fmInfo.fmType]=='undefined'){MUSIC.dom.get('add_favfm').style.display='none';}else{MUSIC.dom.get('add_favfm').style.display='';}
var url=window.location.href.replace(/#.+/g,'');window.location.href=url+'#'+fmInfo.fmId+'_'+fmInfo.fmType;},fm_stat:function(optcode,ltime){if(!g_fmChn._curSongInfo){return;}
var source=g_fmChn.isQplus?1:(g_fmChn.isPengyou?2:0);var ttime=0;if(!!ltime){ttime=ltime;}
g_stat(optcode,g_fmChn._curFmInfo.fmId,g_fmChn._curFmInfo.fmType,g_fmChn._curSongInfo.mid,source,ttime,g_fmChn._curSongInfo.mruleid);},playFm:function(fmInfo){g_fmChn._isLoading=true;g_fmChn.getFmSongList(fmInfo.fmType,fmInfo.fmId,function(songlist){g_fmChn._curSongList=songlist;$.qPlayer.play({list:songlist,isPlay:g_fmChn._isPlayNow,mode:2});g_fmChn._isLoading=false;});},startFm:function(){$.qPlayer.play();if(g_qrcHandlerChn.haveqrc){g_qrcHandlerChn.startAnimFrame('song_lrc');}else if(g_lrcHandlerChn.haveLrc){g_lrcHandlerChn.startAnimFrame('song_lrc');}},pauseFm:function(){$.qPlayer.pause();if(g_qrcHandlerChn.haveqrc){g_qrcHandlerChn.stopAnimFrame();}
if(g_lrcHandlerChn.haveLrc){g_lrcHandlerChn.stopAnimFrame();}},playNext:function(){if(g_fmChn._isLoading){return;}
g_fmChn.fm_stat(5);if(g_fmChn._curFmInfo.fmType==100){g_fmChn._isPlayNow=true;g_fmChn._isAddNextSong=true;if(!!g_fmChn._nextSongInfo){g_fmChn.simrecord.add({songid:g_fmChn._nextSongInfo.mid,actionid:'2',playtime:'1',source:'9'});}
g_fmChn.playFm(g_fmChn._curFmInfo);}else{$.qPlayer.next();}},likeSong:function(){var url='http://stream'+g_fmChn._curSongInfo.mstream+'.qqmusic.qq.com/'+parseInt(12000000+g_fmChn._curSongInfo.mid)+'.wma';g_fmChn.myFavSong.addToMyFavSongList({id:g_fmChn._curSongInfo.mid,type:3,songname:g_fmChn._curSongInfo.msong,singername:g_fmChn._curSongInfo.msinger,diskname:g_fmChn._curSongInfo.malbum,url:url,singerid:g_fmChn._curSongInfo.msingerid,diskid:g_fmChn._curSongInfo.malbumid,playtime:g_fmChn._curSongInfo.minterval});var pt=g_fmChn.playtime.get();g_fmChn.listenrecord.add({songid:g_fmChn._curSongInfo.mid,playtime:pt+'',source:'104',actionid:'7'});if(g_fmChn._curFmInfo.fmType==100){g_fmChn.simrecord.add({songid:g_fmChn._curSongInfo.mid,actionid:'7',playtime:pt+'',source:'104'});g_fmChn._isPlayNow=false;g_fmChn.playFm(g_fmChn._curFmInfo);}},delSong:function(){g_fmChn.myFavSong.delFromFavSongList(g_fmChn._curSongInfo.mid,3);var pt=g_fmChn.playtime.get();g_fmChn.listenrecord.add({songid:g_fmChn._curSongInfo.mid,playtime:pt+'',source:'102',actionid:'9'});if(g_fmChn._curFmInfo.fmType==100){g_fmChn.simrecord.add({songid:g_fmChn._curSongInfo.mid,actionid:'9',playtime:pt+'',source:'102'});g_fmChn._isPlayNow=false;g_fmChn.playFm(g_fmChn._curFmInfo);}},disLikeSong:function(){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(){return function(){g_fmChn.disLikeSong();}})();g_fmChn.login.open_login();return false;}
var pt=g_fmChn.playtime.get();g_fmChn.listenrecord.add({songid:g_fmChn._curSongInfo.mid,playtime:pt+'',source:'102',actionid:'6'});if(g_fmChn._curFmInfo.fmType==100){g_fmChn.simrecord.add({songid:g_fmChn._curSongInfo.mid,actionid:'6',playtime:pt+'',source:'102'});}
g_fmChn.favSong.disLike(g_fmChn._curSongInfo.mid);this.playNext();g_fmChn.fm_stat(4);},shareMusic:function(music){if(typeof music=='undefined'){var _song_info={};MUSIC.object.extend(_song_info,g_fmChn._curSongInfo);g_fmChn.shareMusic(_song_info);return;}
var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(music){return function(){g_fmChn.shareMusic(music);}})(music);g_fmChn.login.open_login();return;}
g_user.getVipInfo(function(data){music.nick=data.nickname;g_dialog.show({mode:"iframe",title:"音乐分享",url:"http://music.qq.com/tips/share_music.html",objArg:music,isLoadCss:false});});var pt=g_fmChn.playtime.get();g_fmChn.listenrecord.add({songid:g_fmChn._curSongInfo.mid,playtime:pt+'',source:'106',actionid:'1'});if(g_fmChn._curFmInfo.fmType==100){g_fmChn.simrecord.add({songid:g_fmChn._curSongInfo.mid,actionid:'1',playtime:pt+'',source:'106'});}},showLyricTips:function(obj){var song_lrc_p=MUSIC.dom.get('song_lrc').parentNode;if(MUSIC.css.hasClassName(song_lrc_p,'showlrc')){MUSIC.css.removeClassName(song_lrc_p,'showlrc');obj.className='btn_lrc';}else{MUSIC.css.addClassName(song_lrc_p,'showlrc');obj.className='btn_lrc_on';}},guessYouLike:function(e){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(){return function(){g_fmChn.setCurChn(0,100,g_fmChn._chnContainer['#0_100']);}})();g_fmChn.login.open_login();MUSIC.event.preventDefault(e);return false;}
var target=MUSIC.event.getTarget(e);this.setCurChn(0,100,target);},setChnAndList:function(fmId,fmType){var node=this._chnContainer['#'+fmId+'_'+fmType];this.setCurChnType(this._fmListInfo[fmId+'_'+fmType]);if(!!node){this.setCurChn(fmId,fmType,node);if(fmType!=100){MUSIC.scrollbar.selectElement(node);}}},setCurChn:function(fmId,fmType,node){this._curChn.className="";this._curChn=node;this._curChn.className="on";if(fmId==0&&fmType==100){MUSIC.dom.get('share_fm').style.display='none';MUSIC.dom.get('guess_text').innerHTML='你正在收听';}else{MUSIC.dom.get('share_fm').style.display='';MUSIC.dom.get('guess_text').innerHTML='不知道听什么？试试';}
var fmInfo={};fmInfo.fmType=fmType;fmInfo.fmId=fmId;fmInfo.fmName=this._fmNameObj[fmId+"_"+fmType];g_fmChn._isPlayNow=true;this.playFm(fmInfo);g_fmChn.updateCurFm(fmInfo);var uin=g_user.getUin();if(uin>10000){g_storage.set('fmchannle'+uin,fmId+'_'+fmType);}},setCurChnType:function(listId){if(!listId){listId=1;}
this._curChnType.className="";this._curChnList.style.display="none";this._curChnType=MUSIC.dom.get("ch_"+listId);this._curChnList=MUSIC.dom.get("content_"+listId);this._curChnType.className="on";this._curChnList.style.display="block";MUSIC.scrollbar.init({barid:"bar",contid:"content",bar_hover:"slider slider_hover",ulid:this._curChnList});},selectFmEvent:function(){var $=MUSIC,$D=$.dom,$E=$.event;$D.get('content').onclick=function(e){var target=$E.getTarget(e);var hrefparts,_fmId,_fmType;if(target.nodeName==='STRONG'||target.nodeName==='EM'){target=target.parentNode;}
if(target.nodeName==='SPAN'){target=target.parentNode;}
if(target.nodeName!=='A'){return;}
hrefparts=target.href.split('#');hrefparts=hrefparts[hrefparts.length-1].split('_');_fmId=hrefparts[0];_fmType=hrefparts[1];g_fmChn.setCurChn(_fmId,_fmType,target);$E.cancelBubble(e);};$D.get('nav').onclick=function(e){var target=$E.getTarget(e);var hrefparts,_fmType;if(target.nodeName!=='A'){return;}
hrefparts=target.href.split('#');_fmType=hrefparts[hrefparts.length-1];g_fmChn.setCurChnType(_fmType);$E.cancelBubble(e);$E.preventDefault(e);};},fm_logout:function(){var ha=window.location.href.lastIndexOf("#"),id,type;if(ha>=0){var hrefparts=window.location.href.substring(ha+1);hrefparts=hrefparts.split('_');id=hrefparts[0];type=hrefparts[1];}
if(id==0&&type==100){g_fmChn.setChnAndList(118,1);}
var elem=MUSIC.dom.get("divuserinfo");if(elem){elem.innerHTML='<a href="javascript:;" onclick="g_fmChn.login.open_login();" >登录</a>';}
g_fmChn._myFavFm.innerHTML='我收藏的电台';g_fmChn._myFavSong.innerHTML='我喜欢';g_fmChn._songRecord.innerHTML='我听过的歌';g_fmChn.songRecord.clear();g_fmChn._btnLike.onclick=g_fmChn.likeSong;g_fmChn._btnLike.className="btn_like";g_fmChn._btnLike.title="喜欢";},statArrPush:function(){for(var i=0,len=arguments.length;i<len&&i<g_fmChn._statArrNum;i++){if(g_fmChn._statArr[i]!=''){g_fmChn._statArr[i]+=',';}
g_fmChn._statArr[i]+=arguments[i];}},firstBuffered:function(startTime,endTime){if(g_fmChn._statArr[0].split(',').length>=10){return;}
var source=g_fmChn.isQplus?1:(g_fmChn.isPengyou?2:0);g_fmChn.statArrPush(g_fmChn._curFmInfo.fmId,g_fmChn._curFmInfo.fmType,g_fmChn._curSongInfo.mid,11,source,endTime-startTime,g_fmChn._curSongInfo.mruleid);},secondBuffered:function(startTime,endTime){if(g_fmChn._statArr[0].split(',').length>=10){return;}
var source=g_fmChn.isQplus?1:(g_fmChn.isPengyou?2:0);g_fmChn.statArrPush(g_fmChn._curFmInfo.fmId,g_fmChn._curFmInfo.fmType,g_fmChn._curSongInfo.mid,12,source,endTime-startTime,g_fmChn._curSongInfo.mruleid);},showNextSongInfo:function(){if(!!g_fmChn._nextSongInfo){var nsong=g_fmChn._nextSongInfo;MUSIC.dom.get('song_reason').innerHTML='下一首：'+nsong.msong.unescapeHTML()+' - '+nsong.msinger.unescapeHTML();MUSIC.dom.get('song_reason').title='下一首：'+nsong.msong.unescapeHTML()+' - '+nsong.msinger.unescapeHTML();showElement('song_reason');}},isShowLrc:function(fmId,fmType){if(fmType!=1){return true;}
return(fmId!=174&&fmId!=175&&fmId!=176&&fmId!=181&&fmId!=207&&fmId!=129);}}
MUSIC.channel.fm.favFm={add:function(fmInfo,callback){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(fmInfo,callback){return function(){g_fmChn.favFm.add(fmInfo,callback);}})(fmInfo,callback);g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"收藏电台失败！","当前网络繁忙，请您稍后重试。",1000,300,true,false);}
function _succ(){g_popup.show(0,"收藏电台成功！","",1000,200,true,false);}
function _succ2(){g_popup.show(1,"您已经收藏过该电台！","",1000,260,true,false);}
var url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_musicradio_add.fcg?uin="+uin+"&radioid="+fmInfo.fmId+"&owneruin="+uin+"&type="+fmInfo.fmType+"&out=1&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"favFmadd",null,"gb2312",false);j.onSuccess=function(data){if(data.code==0){_succ();if(callback){callback();}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);}else if(data.code==6||data.code==9){_succ2();}else if(data.code==2){g_user.callback=(function(fmInfo,callback){return function(){g_fmChn.favFm.add(fmInfo,callback);}})(fmInfo,callback);g_fmChn.login.open_login();}else{_error();}};j.onError=_error;j.send("addMusicRadioCallback");},del:function(fmInfo,callback){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(fmInfo,callback){return function(){g_fmChn.favFm.del(fmInfo,callback);}})(fmInfo,callback);g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"删除电台失败！","当前网络繁忙，请您稍后重试。",1000,260,true,false);}
function _succ(){g_popup.show(0,"删除电台成功！","",1000,240,true,false);}
var url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_musicradio_delete.fcg",data={uin:uin,radioid:fmInfo.fmId,owneruin:uin,type:fmInfo.fmType,out:2,formsender:1},fs=new MUSIC.FormSender(url,"post",data,"GB2312");fs.onSuccess=function(o){if(o.code==0){_succ();if(callback){callback(o);}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);}else if(o.code==2){g_user.callback=(function(fmInfo,callback){return function(){g_fmChn.favFm.del(fmInfo,callback);}})(fmInfo,callback);g_fmChn.login.open_login();}else{_error();}};fs.onError=_error;fs.send();},getUserFavNum:function(callback){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"获取我收藏的电台列表信息失败！","当前网络繁忙，请您稍后重试。",1000,350,true,false);}
var url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_musicradiobyuin_getinfo.fcg?uin="+uin+"&out=1&dirid=201&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"getUserFavNum",null,"gb2312",false);j.onSuccess=function(data){if(data.code==0){if(callback){callback(data.num,data.song_num);}}else if(data.code==2){g_fmChn.login.open_login();}else{_error();}};j.onError=_error;j.send("GetMusicRadioInfoByuinCallback");},getFmFavNum:function(fmInfo,callback){function _error(){g_popup.show(1,"获取电台收藏人数失败！","当前网络繁忙，请您稍后重试。",1000,350,true,false);}
var url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_musicradio_getinfo.fcg?radioid="+fmInfo.fmId+"&type="+fmInfo.fmType+"&out=1&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"getFmFavNum",null,"gb2312",false);j.onSuccess=function(data){if(data.retcode==0){callback();}else{_error();}};j.onError=_error;j.send("jsonCallback");},getList:function(callback){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"获取电台收藏列表失败！","当前网络繁忙，请您稍后重试。",1000,350,true,false);}
var url="http://radio.cloud.music.qq.com/fcgi-bin/fcg_musicradiolist_getinfo.fcg?uin="+uin+"&out=1&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"getList",null,"gb2312",false);j.onSuccess=function(data){if(data.code==0){if(callback){callback(data);}}else if(data.code==2){g_fmChn.login.open_login();}else{_error();}};j.onError=_error;j.send("GetMusicRadioListInfoCallback");}}
MUSIC.channel.fm.favSong={add:function(idlist,typelist,callback){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(idlist,typelist,callback){return function(){g_fmChn.favSong.add(idlist,typelist,callback);}})(idlist,typelist,callback);g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"操作失败，服务器繁忙，请稍后再试。","",1000,400,true,false);}
function _succ(){g_popup.show(0,"喜欢成功","歌曲已添加到您的“我喜欢”列表。",1000,350,true,false);}
var url="http://s.plcloud.music.qq.com/fcgi-bin/fcg_music_add2songdir.fcg",data={uin:uin,dirid:201,idlist:idlist,source:104,typelist:typelist,formsender:1,utf8:1},fs=new MUSIC.FormSender(url,"post",data,"utf-8");fs.onSuccess=function(o){switch(o.code)
{case 0:if(idlist==g_fmChn._curSongInfo.mid){g_fmChn._btnLike.className="btn_like_on";g_fmChn._btnLike.title="取消喜欢";g_fmChn._btnLike.onclick=g_fmChn.delSong;}
if(callback){callback();}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);g_fmChn.fm_stat(2);break;case 1:g_user.callback=(function(idlist,typelist,callback){return function(){g_fmChn.favSong.add(idlist,typelist,callback);}})(idlist,typelist,callback);g_fmChn.login.open_login();break;case 31:case 32:case 41:var t=o.title?o.title:"对不起，操作失败！",v='<a href="http://pay.qq.com/music/index.shtml?aid=music.bfq.gdsx.1&clientuin="'+uin+' target="_blank" title="开通绿钻，畅享无限空间>>">开通绿钻，畅享无限空间>></a>'
msg=o.msg?o.msg:"";(!!o.title&&msg!="")&&(msg+=v);g_popup.show(1,t,msg,3000,500,true,false);break;default:_error();break;}};fs.onError=_error;fs.send();},del:function(idlist,typelist,callback){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(idlist,typelist,callback){return function(){g_fmChn.favSong.del(idlist,typelist,callback);}})(idlist,typelist,callback);g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"操作失败，服务器繁忙，请稍后再试。","",1000,400,true,false);}
function _succ(){g_popup.show(0,"取消成功","",1000,180,true,false);}
var url="http://qzone-music.qq.com/fcg-bin/fcg_music_delbatchsong.fcg",data={uin:uin,dirid:201,ids:idlist,source:103,types:typelist,formsender:1,flag:2,from:3,utf8:1},fs=new MUSIC.FormSender(url,"post",data,"utf-8");fs.onSuccess=function(o){switch(o.code)
{case 0:if(idlist==g_fmChn._curSongInfo.mid){g_fmChn._btnLike.className="btn_like";g_fmChn._btnLike.title="喜欢";g_fmChn._btnLike.onclick=g_fmChn.likeSong;}
if(callback){callback();}
g_fmChn.updateMyFavNum(g_fmChn.myFavFm.idList.length,g_fmChn.myFavSong.songList.length);g_fmChn.fm_stat(8);break;case 1:g_user.callback=(function(idlist,typelist,callback){return function(){g_fmChn.favSong.del(idlist,typelist,callback);}})(idlist,typelist,callback);g_fmChn.login.open_login();break;default:_error();break;}};fs.onError=_error;fs.send();},getList:function(callback){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
function _error(){g_popup.show(1,"获取我喜欢的列表信息失败！","当前网络繁忙，请您稍后重试。",1000,350,true,false);}
var url="http://s.plcloud.music.qq.com/fcgi-bin/fcg_musiclist_getinfo.fcg?uin="+uin+"&dirid=201&dirinfo=1&user=qqmusic&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"favsonglist",null,"gb2312",false);j.onSuccess=function(data){if(data.code==0){if(callback){callback(data);}}else if(data.code==2){g_fmChn.login.open_login();}else{_error();}};j.onError=_error;j.send("jsonCallback");},disLike:function(id){var uin=g_user.getUin();if(uin<10001){g_user.callback=(function(id){return function(){g_fmChn.favSong.disLike(id);}})(id);g_fmChn.login.open_login();return;}
function _error(){}
var url="http://portalcgi.music.qq.com/fcgi-bin/radio/cgi_radio_dislike.fcg?songid="+id+"&rnd="+new Date().valueOf(),j=new MUSIC.JSONGetter(url,"disLike",null,"gb2312",false);j.onSuccess=function(data){if(data.code==0){}else if(data.code==1){g_user.callback=(function(id){return function(){g_fmChn.favSong.disLike(id);}})(id);g_fmChn.login.open_login();}else{_error();}};j.onError=_error;j.send("MusicJsonCallback");}}
window.on_login=function(){g_fmChn.showUserInfo();g_fmChn._callback_counter=0;if(g_fmChn._callback_timer){clearTimeout(g_fmChn._callback_timer);g_fmChn._callback_timer=null;}
g_fmChn._callback_timer=setTimeout(checkCallBack,50);}
window.checkCallBack=function(){if(g_fmChn._callback_counter>=3){if(g_user.callback){g_user.callback();g_user.callback=null;}
g_fmChn._callback_counter=0;if(g_fmChn._callback_timer){clearTimeout(g_fmChn._callback_timer);g_fmChn._callback_timer=null;}}else{if(g_fmChn._callback_timer){clearTimeout(g_fmChn._callback_timer);g_fmChn._callback_timer=null;}
g_fmChn._callback_timer=setTimeout(checkCallBack,50);}}
MUSIC.channel.fm.playtime=(function(){var playingC=0;var curtime=0;var totaltime=0;function set(cur,total){if(playingC>0&&cur==0){return;}
curtime=cur;if(playingC==0){totaltime=total;}
playingC++;}
function end(){playingC=0;curtime=0;totaltime=0;}
function get(){if(playingC==0){return 0;}
if(playingC>0&&curtime==0){return totaltime;}
return curtime;}
return{get:get,set:set,end:end}})();MUSIC.channel.fm.listenrecord=(function(){var record_num=100;var songidlist=[];var playtimelist=[];var sourcelist=[];var actionidlist=[];function formatStr(){return[songidlist.join(','),playtimelist.join(','),sourcelist.join(','),actionidlist.join(',')].join('|');}
function get(callback){var uin=g_user.getUin();g_storage.get('fmlistenrecord'+uin,function(record){record=record||'';if(record!=''){var arr=record.split('|');songidlist=arr[0].split(',');playtimelist=arr[1].split(',');sourcelist=arr[2].split(',');actionidlist=arr[3].split(',');}else{clear();}
callback();});}
function set(){var uin=g_user.getUin();if(songidlist.length>0){g_storage.set('fmlistenrecord'+uin,formatStr());}else{g_storage.set('fmlistenrecord'+uin,'');}}
function clear(){songidlist=[];playtimelist=[];sourcelist=[];actionidlist=[];}
function add(obj){if(!(typeof obj.songid!='undefined')&&(typeof obj.playtime!='undefined')&&(typeof obj.actionid!='undefined')&&!!obj.source){return;}
get(function(){songidlist.push(obj.songid);playtimelist.push(obj.playtime);sourcelist.push(obj.source);actionidlist.push(obj.actionid);if(songidlist.length>record_num){songidlist.splice(0,1);playtimelist.splice(0,1);sourcelist.splice(0,1);actionidlist.splice(0,1);}
set();});}
function report(){get(function(){if(songidlist.length>0&&g_user.getUin()>10000){var url='http://s.plcloud.music.qq.com/fcgi-bin/fcg_fm_report_record.fcg',data={uin:g_user.getUin(),songid:songidlist.join(','),source:sourcelist.join(','),playtime:playtimelist.join(','),actionid:actionidlist.join(','),num:songidlist.length,utf8:1},fs=new MUSIC.FormSender(url,"post",data,"utf-8");fs.onSuccess=function(o){}
fs.onError=function(){};fs.send();clear();set();}});setTimeout(function(){g_fmChn.listenrecord.report();},60000);}
return{add:add,report:report}})();MUSIC.channel.fm.simrecord=(function(){var record_num=19;var songidlist=[];var actionidlist=[];var opertimelist=[];var sourcelist=[];var playtimelist=[];function getHistoryList(callback){get(function(){var arr=[];for(var i=0,len=songidlist.length;i<len;i++){arr.push([songidlist[i],actionidlist[i],opertimelist[i],sourcelist[i],playtimelist[i]].join('|'));}
if(!!g_fmChn._curSongInfo&&g_fmChn._curSongInfo.mid>0){arr.push([g_fmChn._curSongInfo.mid,'2',Math.round(new Date().getTime()/1000),'9',g_fmChn.playtime.get()].join('|'));}
arr=arr.reverse();callback(arr.join(','));});}
function formatStr(){return[songidlist.join(','),actionidlist.join(','),opertimelist.join(','),sourcelist.join(','),playtimelist.join(',')].join('|');}
function get(callback){var uin=g_user.getUin();g_storage.get('fmsimrecord'+uin,function(record){record=record||'';if(record!=''){var arr=record.split('|');songidlist=arr[0].split(',');actionidlist=arr[1].split(',');opertimelist=arr[2].split(',');sourcelist=arr[3].split(',');playtimelist=arr[4].split(',');}else{clear();}
callback();});}
function set(){var uin=g_user.getUin();if(songidlist.length>0){g_storage.set('fmsimrecord'+uin,formatStr());}else{g_storage.set('fmsimrecord'+uin,'');}}
function clear(){songidlist=[];actionidlist=[];opertimelist=[];sourcelist=[];playtimelist=[];}
function add(obj){if(!(typeof obj.songid!='undefined')&&(typeof obj.actionid!='undefined')&&(typeof obj.playtime!='undefined')&&!!obj.source){return;}
get(function(){songidlist.push(obj.songid);actionidlist.push(obj.actionid);opertimelist.push(Math.round(new Date().getTime()/1000));sourcelist.push(obj.source);playtimelist.push(obj.playtime);if(songidlist.length>record_num){songidlist.splice(0,1);actionidlist.splice(0,1);opertimelist.splice(0,1);sourcelist.splice(0,1);playtimelist.splice(0,1);}
set();});}
return{add:add,getHistoryList:getHistoryList}})();MUSIC.channel.fm.keeplogin=(function(){function keep(){setTimeout(function(){if(g_user.getUin()>10000){var url="http://s.plcloud.music.qq.com/fcgi-bin/keep_login_state.fcg?rnd="+new Date().valueOf();new Image().src=url;}
g_fmChn.keeplogin.keep();},2400000);}
return{keep:keep}})();MUSIC.channel.fm.songRecord=(function(){var songIdMap={};var idcount=0;var songListInfo={};var _songlist=[];var _tpl=['<div class="hint">想找以前听过的一首好歌却偏偏想不起来？不用郁闷！<p>QQ音乐电台自动记录你的听歌历史，听过什么歌都能一目了然，还可以方便地标记为我喜欢</p></div>','<div class="songlist">','<ul id="record_songlist">','</ul>','</div>','<div class="pager" id="record_pager">','</div>'].join('');var _title='<span>我听过的歌</span><a href="javascript:;" onclick="g_fmChn.songRecord.playAll();" class="icon_playall" id="play_all" >全部播放</a>';var _song_tpl='<li><span class="songname" title="%(msong)">%(msong)</span><span class="artists" title="%(msinger)">%(msinger)</span><span class="album" title="%(malbum)">%(malbum)</span><span class="like"><a href="javascript:;" class="%(icon_class)" title="%(desc)" onclick="g_fmChn.songRecord.clickLike(this,%(mid));">%(desc)</a></span></li>';function clear(){songIdMap={};idcount=0;songListInfo={};_songlist=[];}
function getNum(callback){var uin=g_user.getUin();var url='http://s.plcloud.music.qq.com/fcgi-bin/fmuin_song.fcg?utf8=1&uin='+uin+'&from=0&to=1000&type=0&rnd='+new Date().valueOf();function _error(){callback(idcount);}
var j=new MUSIC.JSONGetter(url,"songrecord",null,"utf-8",false);j.onSuccess=function(data){if(data.code==0&&data.num>0){var arr=data.ids.split(',');for(var i=0,len=arr.length;i<len;i++){if(songIdMap[arr[i]]!=1){idcount++;}
songIdMap[arr[i]]=1;}}
callback(idcount);};j.onError=function(){_error();};j.send("GetMusicRadioInfoCallback");}
function addSongId(id,callback){if(songIdMap[id]!=1&&idcount<1000){idcount++;}
songIdMap[id]=1;callback(idcount);}
function clickLike(obj,id){var song=songListInfo[id];if(obj.className=='icon_unlike'){g_fmChn.myFavSong.addToMyFavSongList({id:song.mid,type:3,songname:song.msong,singername:song.msinger,diskname:song.malbum,url:song.url,singerid:song.msingerid,diskid:song.malbumid,playtime:song.minterval});obj.className='icon_like';obj.title='取消喜欢';obj.innerHTML='取消喜欢';}else{g_fmChn.myFavSong.delFromFavSongList(song.mid,3);obj.className='icon_unlike';obj.title='标记喜欢';obj.innerHTML='标记喜欢';}}
function getSongList(from,to,callback){var uin=g_user.getUin();var url='http://s.plcloud.music.qq.com/fcgi-bin/fmuin_song.fcg?utf8=1&uin='+uin+'&from='+from+'&to='+to+'&type=3&rnd='+new Date().valueOf();function formatMusic(songdata){var _arrSongAttr=["mid","msong","msingerid","msinger","malbumid","malbum","msize","minterval","mstream","mdownload","msingertype","size320","size128","mrate","gososo","sizeape","sizeflac","sizeogg"];var length=_arrSongAttr.length,arrMusic=songdata.split("|"),_obj={},i=0,_length=Math.min(length,arrMusic.length);for(i=0;i<_length;i++){_obj[_arrSongAttr[i]]=arrMusic[i];}
for(i=_length;i<length;i++){_obj[_arrSongAttr[i]]="";}
return _obj;};function _error(){g_popup.show(1,"获取电台听歌信息失败！","当前网络繁忙，请您稍后重试。",1000,320,true,false);}
var j=new MUSIC.JSONGetter(url,"songrecordlist",null,"utf-8",false);j.onSuccess=function(data){_songlist=[];songListInfo={};if(data.code==0){MUSIC.object.each(data.SongList,function(info){var _data=formatMusic(unescape(unescape(info.data)).replace(/\+/ig," "));_data.url='http://stream'+_data.mstream+'.qqmusic.qq.com/'+parseInt(12000000+parseInt(_data.mid))+'.wma';_data.type=3;_songlist.push(_data);songListInfo[_data.mid]=_data;});callback({total_num:data.TotalSongNum,songlist:_songlist});}else if(data.code==2){g_fmChn.login.open_login();return;}else{_error();}};j.onError=function(){_error();};j.send("GetMusicRadioInfoCallback");}
function getPager(pageNum,totalNum){if(totalNum<2){return'';}
var navHTML=[];for(var i=1;i<=totalNum;i++){if(i!=pageNum){navHTML.push('<a href="javascript:;" onclick="g_fmChn.songRecord.showPage('+i+')">'+i+'</a>');}else{navHTML.push('<a href="javascript:;"  class="on">'+i+'</a>');}}
if(totalNum>13){if(pageNum>7){navHTML.splice(1,pageNum-7,'<a href="javascript:;">...</a>');if(totalNum-pageNum>6){navHTML.splice(13,totalNum-6-pageNum,'<a href="javascript:;">...</a>');}}else{if(totalNum-pageNum>6){navHTML.splice(pageNum+5,totalNum-6-pageNum,'<a href="javascript:;">...</a>');}}}
navHTML.unshift('<span class="num">');navHTML.push('</span>');if(pageNum>1){navHTML.unshift('<a href="javascript:;" onclick="g_fmChn.songRecord.showPage('+parseInt(pageNum-1)+')">上一页</a>');}
if(pageNum<totalNum){navHTML.push('<a href="javascript:;" onclick="g_fmChn.songRecord.showPage('+parseInt(pageNum+1)+')">下一页</a>');}
return navHTML.join('');}
function showPage(pageNum){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
if(pageNum<1){return;}
var from=(pageNum-1)*10,to=pageNum*10-1;getSongList(from,to,function(data){var html=[];for(var i=0,len=data.songlist.length;i<len;i++){var item=data.songlist[i];item.icon_class='icon_unlike';item.desc='标记喜欢';if(g_fmChn.myFavSong.isInSongList(item.mid)){item.icon_class='icon_like';item.desc='取消喜欢';}
html.push(_song_tpl.jstpl_format(item));}
MUSIC.dom.get('record_songlist').innerHTML=html.join('');MUSIC.dom.get('record_pager').innerHTML=getPager(pageNum,Math.ceil(data.total_num/10));});}
function show(){var uin=g_user.getUin();if(uin<10001){g_fmChn.login.open_login();return;}
g_dialog.show({mode:"bigpage",title:_title,desc:_tpl,width:600,isLoadCss:false});showPage(1);}
function playAll(){if(_songlist.length>0){var songinfo_list=[];for(var i=0,len=_songlist.length;i<len;i++){var tmp=_songlist[i];songinfo_list.push([tmp.mid,tmp.type,tmp.url,tmp.msong,tmp.msingerid,tmp.msinger,tmp.malbumid,tmp.malbum,tmp.minterval]);}
if(songinfo_list.length>0){g_fmChn.myFavSong.openEmptyWindow("_webQQMusicPlayer");g_fmChn.myFavSong.addSoSoPlaylist(songinfo_list,{songList:'',type:1,vip:-1,userName:'',playXsosoFlag:0,source:9,u:g_user.getUin()>1000?g_user.getUin():34567890,k:0});}}}
return{getNum:getNum,showPage:showPage,show:show,clickLike:clickLike,playAll:playAll,addSongId:addSongId,clear:clear}})();MUSIC.channel.fm.login=(function(){function on_login(){g_fmChn.showUserInfo();g_fmChn._callback_counter=0;if(g_fmChn._callback_timer){clearTimeout(g_fmChn._callback_timer);g_fmChn._callback_timer=null;}
g_fmChn._callback_timer=setTimeout(checkCallBack,50);}
function open_login(){g_user.openLogin(null,'self',g_fmChn.login.on_login);}
return{on_login:on_login,open_login:open_login}})();var g_fmChn=MUSIC.channel.fm;MUSIC.config.DCCookieDomain="fm.qq.com";MUSIC.channel.lrcHandler=(function(){function sortFunc(obj1,obj2){return(g_lrcHandlerChn.compare(obj1.time,obj2.time)?-1:1);}
function getTime(){return g_webPlayer.getCurPostion();}
return function(){var _this=this,$D=MUSIC.dom,$E=MUSIC.event;_this.reqFlag=-1;_this.haveLrc=false;_this.lyricData='';_this.lrcItem={time:'00:00.00',context:''};_this.lrcItemIndex=0;_this.preLrcItemIndex=-1;_this.lrcList=[];_this.artist='';_this.songTitle='';_this.album='';_this.byBody='';_this.offset=0;_this.playingSong=0;_this.init=function(songId){_this.clearLrcInfo();_this.playingSong=songId;_this.loadLyricBySongId(songId,_this.dealLrcXmlSucc,_this.dealLrcXmlFail);};_this.loadLyricBySongId=function(songId,succCallback,errCallback){if(typeof errCallback!=='Funciton'){errCallback=_this.dealLrcXmlFail;}
try{(!top['qqmusic_lyrics_lrc'+songId])&&(top['qqmusic_lyrics_lrc'+songId]=null);}catch(e){}
var _data=null;try{_data=top['qqmusic_lyrics_lrc'+songId];}catch(e){_data=null;}
if(!!_data){_this.reqFlag=1;_this.haveLrc=true;if(_data=='no-lyrics'){errCallback();return;}
_data=g_coder.Base64.decode(_data);succCallback(_data);return;}
_this.reqFlag=0;var _url="http://portalcgi.music.qq.com/fcgi-bin/fcg_query_lyric.fcg?musicid="+songId+"&pcachetime="+(new Date().getTime()),_jMode=(!!ua.safari||!!ua.chrome||!!ua.isiPad||!!ua.isiPhone||!!ua.firefox)?true:false;var xmlAjax=new MUSIC.JSONGetter(_url,'song_lyrics',null,'utf-8',_jMode);xmlAjax.timeout=3000;xmlAjax.onSuccess=function(data){if(!!data&&data.retcode==0){if(data.type!=3){_this.reqFlag=1;_this.haveLrc=true;_data=data.lyric;try{top['qqmusic_lyrics_lrc'+songId]=_data;}catch(e){}
_data=g_coder.Base64.decode(_data);succCallback(_data);}else{errCallback();}}else{errCallback();}};xmlAjax.onTimeout=function(){xmlAjax._waiting=false;errCallback();}
xmlAjax.onError=errCallback;xmlAjax.send("MusicJsonCallback");};_this.dealLrcXmlSucc=function(xmlHttp){var _originLyric=xmlHttp;if(!!_originLyric){_this.lyricData=_originLyric.replace(new RegExp("\\n","g"),"_!!_").trim();_this.parseLyricData();}};_this.dealLrcXmlFail=function(){g_lrcHandlerChn.reqFlag=1;g_lrcHandlerChn.haveLrc=false;try{top['qqmusic_lyrics_lrc'+_this.playingSong]=null;}catch(e){}};_this.parseLyricData=function(){var _lrcData=_this.lyricData,_tmpList=[],i=0,_len=0,_cache;_tmpList=_lrcData.split('_!!_');for(_len=_tmpList.length;i<_len;i++){_cache=_tmpList[i];var _rIndex=_cache.lastIndexOf(']'),_lSubstr=_cache.substring(0,_rIndex+1),_rSubstr=_cache.substring(_rIndex+1),_tmpTimes=_lSubstr.replace(new RegExp("\\[","g"),"").split(']'),_tLen=_tmpTimes.length,j=_tLen-1,_tmpTag='',_pointPos=0;while(j--){_tmpTag=_tmpTimes[j];if(_tmpTag.indexOf('al:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.album=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('ar:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.artist=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('ti:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.songTitle=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('by:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.byBody=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('offset:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.offset=_tmpTag.substring(_pointPos+1);}else{_tmpTag=(_tmpTag.indexOf(".")!=-1)?_tmpTag:_tmpTag+".00";_rSubstr=_rSubstr.trim()==''?'......':_rSubstr.trim();var _t=parseInt((_this.playTime2ms(_tmpTag)-_this.offset),10);_tmpTag=_this.ms2playTime(_t);_this.lrcList.push({time:_tmpTag,context:_rSubstr});}}}
_this.sortLrcList();};_this.sortLrcList=function(){_this.lrcList.sort(sortFunc);};_this.printLrcLines=function(){var _list=_this.lrcList;if(!!_list){var _len=_list.length,i=0,_html=[];for(;i<_len;i++){_html.push('<p id="line_'+i+'"><span>'+_list[i].context+'</span></p>');}
return _html.join('');}
return'';};_this.clearLrcInfo=function(){_this.haveLrc=false;_this.lrcList=[];_this.lyricData='';_this.artist='';_this.songTitle='';_this.album='';_this.byBody='';_this.offset=0;_this.preLrcItemIndex=-1;_this.lrcItemIndex=0;_this.reqFlag=-1;_this.stopAnimFrame();};_this.clearLrcItem=function(){_this.lrcItem={time:'00:00.00',context:''};};_this.getLyricLineItemByLineIndex=function(lineIndex){var _len=_this.lrcList.length;if(lineIndex<0||lineIndex>=_len){return false;}
_this.clearLrcItem();(_this.lrcItemIndex<lineIndex)&&(_this.preLrcItemIndex=_this.lrcItemIndex);_this.lrcItemIndex=lineIndex;_this.lrcItem=_this.lrcList[_this.lrcItemIndex];return true;};_this.getLyricLineItemByTimes=function(minutes,seconds,mSecond){if(minutes<0||seconds<0||mSecond<0){return false;}
_this.clearLrcItem();var _curPlayTime=minutes+':'+seconds+'.'+mSecond;return _this.getLyricLineItemByPlayTime(_curPlayTime);};_this.getLyricLineItemByPlayTime=function(playTime){_this.clearLrcItem();var _curPlayTime=playTime,_lrcItemCount=_this.lrcList.length,_lineIndex=0,i=0;if(_lrcItemCount<=0){return false;}
for(;i<_lrcItemCount-1;i++){if(0==i&&_this.compare(_curPlayTime,_this.lrcList[i].time,'<')){return _this.getLyricLineItemByLineIndex(0);}
var _startItem=_this.lrcList[i],_endItem=_this.lrcList[i+1];if(_this.compare(_startItem.time,_curPlayTime,'<=')&&_this.compare(_curPlayTime,_endItem.time,'<')){_lineIndex=i;return _this.getLyricLineItemByLineIndex(_lineIndex);}}
if(_this.compare(_this.lrcList[_lrcItemCount-1].time,_curPlayTime)){_lineIndex=_lrcItemCount-1;return _this.getLyricLineItemByLineIndex(_lineIndex);}
return false;};_this.playTime2ms=function(playTime){var _minutes=parseInt(playTime.substring(0,playTime.indexOf(':')),10)*60*1000,_seconds=parseInt(playTime.substring(playTime.indexOf(':')+1,playTime.indexOf('.')),10)*1000,_mSecond=parseInt(playTime.substring(playTime.indexOf('.')+1),10);return(_minutes+_seconds+_mSecond);};_this.ms2playTime=function(ms){var _minutes=parseInt(ms/60000,10),_seconds=parseInt((ms/1000)%60,10),_mSecond=ms-_minutes*60000-_seconds*1000;return(_minutes>9?'':'0')+_minutes+":"+(_seconds>9?'':'0')+_seconds+"."+(_mSecond>9?'':'0')+_mSecond;};_this.compare=function(pt1,pt2,opt){opt=opt||"<=";if("<"==opt){return(_this.playTime2ms(pt1)<_this.playTime2ms(pt2));}else if("<="==opt){return(_this.playTime2ms(pt1)<=_this.playTime2ms(pt2));}else if(">"==opt){return(_this.playTime2ms(pt1)>_this.playTime2ms(pt2));}else if(">="==opt){return(_this.playTime2ms(pt1)>=_this.playTime2ms(pt2));}};_this.scrollLine=function(elem){elem=(typeof elem=='string')?$D.get(elem):elem;var max=parseInt(elem.scrollHeight-72),_top=elem.scrollTop,_line_height=(!!$D.get('line_'+g_lrcHandlerChn.lrcItemIndex))?$D.get('line_'+g_lrcHandlerChn.lrcItemIndex).offsetHeight:24,stop=false,_idx=g_lrcHandlerChn.lrcItemIndex||0,heights=0,_times=parseInt(_line_height/6,10),_off=_line_height%6;while(_idx-->0){heights+=(!!$D.get('line_'+_idx))?$D.get('line_'+_idx).offsetHeight:24;}
stop=(_top==heights);if(!stop){if(heights-_top>=_line_height*2){elem.scrollTop=heights;}else{var _diff=heights-_top;if(_diff>_line_height){_diff-=_line_height;}
var _t=(_diff>=_times)?_times:_off;elem.scrollTop=_top+_t;}}
g_lrcHandlerChn.startAnimFrame(elem);};_this.aniFrame=null;_this.lrcAnimFrame=function(cb,delay){return window.requestTimeout(cb,delay);};_this.startAnimFrame=function(elem){g_lrcHandlerChn.aniFrame=g_lrcHandlerChn.lrcAnimFrame(function(){g_lrcHandlerChn.scrollLine(elem);},delay);};_this.stopAnimFrame=function(){if(g_lrcHandlerChn.aniFrame!=null){window.cancelRequestAnimFrame(g_lrcHandlerChn.aniFrame);}
g_lrcHandlerChn.aniFrame=null;};_this.restartAnimFrame=function(elem){g_lrcHandlerChn.stopAnimFrame();g_lrcHandlerChn.startAnimFrame(elem);};}})();var g_lrcHandlerChn=new MUSIC.channel.lrcHandler();MUSIC.channel.qrcHandler=(function(){function parseTxt2XML(xmlText){var xmlDoc;if(typeof xmlText=='undefined'||''==xmlText){return;}
if(window.DOMParser){parser=new DOMParser();xmlDoc=parser.parseFromString(xmlText,"text/xml");}else{xmlDoc=new ActiveXObject("Microsoft.XMLDOM");xmlDoc.async="false";xmlDoc.loadXML(xmlText);}
return xmlDoc;}
function getTime(){return g_webPlayer.getCurPostion();}
return function(){var _this=this,$D=MUSIC.dom,$E=MUSIC.event;_this.playingSong=0;_this.reqFlag=false;_this.haveqrc=false;_this.qrcData='';_this.qrcJson={ar:'',ti:'',al:'',by:'',offset:'',lines:[]};_this.lineItem={timeTag:{startTime:0,timeLen:0},context:'',wordsItem:[]};_this.wordItem={word:'',startTime:0,timeLen:0};_this.qrcLineIndex=0;_this.artist='';_this.songTitle='';_this.album='';_this.byBody='';_this.offset=0;_this.qrcContainer='';_this.init=function(opt){_this.playingSong=opt.songId;_this.qrcContainer=opt.qrcContainer;_this.clearQrcInfo();_this.loadLyricsBySongId(opt.songId,_this.dealLyricsSucc,_this.dealLyricsFail);};_this.loadLyricsBySongId=function(songId,succCallback,errCallback){if(typeof errCallback!=='Funciton'){errCallback=_this.dealLyricsFail;}
try{(!top['qqmusic_lyrics_qrc'+songId])&&(top['qqmusic_lyrics_qrc'+songId]='');}catch(e){}
var _data=null,_lyric=null;try{_data=top['qqmusic_lyrics_qrc'+songId];_lyric=top['qqmusic_lyrics_lrc'+songId];}catch(e){_data=null;_lyric=null;}
if(!!_data){_data=g_coder.Base64.decode(_data);_this.reqFlag=false;_this.haveqrc=true;succCallback(_data);return;}else if(!!_lyric){errCallback();return;}
_this.reqFlag=true;var _url="http://portalcgi.music.qq.com/fcgi-bin/fcg_query_lyric.fcg?musicid="+songId+"&pcachetime="+(new Date().getTime()),_jMode=(!!ua.safari||!!ua.chrome||!!ua.isiPad||!!ua.isiPhone||!!ua.firefox)?true:false;var xmlAjax=new MUSIC.JSONGetter(_url,'song_lyrics',null,'utf-8',_jMode);xmlAjax.timeout=3000;xmlAjax.onSuccess=function(data){if(!!data&&data.retcode==0){if(data.type==3){_this.reqFlag=false;_this.haveqrc=true;_data=data.lyric;try{top['qqmusic_lyrics_qrc'+songId]=_data;}catch(e){}
_data=g_coder.Base64.decode(_data);succCallback(_data);}else{errCallback();if(!!data.lyric){try{top['qqmusic_lyrics_lrc'+songId]=data.lyric;}catch(e){}}}}else if(!!data&&data.retcode==1){errCallback();try{top['qqmusic_lyrics_lrc'+songId]="no-lyrics";}catch(e){}}else{errCallback();}};xmlAjax.onTimeout=function(){xmlAjax._waiting=false;errCallback();}
xmlAjax.onError=errCallback;xmlAjax.send("MusicJsonCallback");};_this.dealLyricsSucc=function(xmlHttp){var _xmlDom=parseTxt2XML(xmlHttp);if(_xmlDom==undefined||typeof(_xmlDom)=="undefined")
{_this.dealLyricsFail();return;}
var _QrcInfo=_xmlDom.getElementsByTagName("LyricInfo");var _originQrc='';if(!!_QrcInfo[0]){_originQrc=_QrcInfo[0].getElementsByTagName("Lyric_1")[0];}else{_this.dealLyricsFail();return;}
if(!!_originQrc){_this.qrcData=_originQrc.getAttribute('LyricContent');_this.parseQrcData();}};_this.dealLyricsFail=function(){_this.reqFlag=false;_this.haveqrc=false;try{top['qqmusic_lyrics_qrc'+_this.playingSong]=null;}catch(e){}};_this.parseQrcData=function(){var _qrcData=_this.qrcData,_tmpLineObj={},i=0,_len=0,_cache={};_tmpLineObj=_this.getLineFlag(_qrcData);var _reg=new RegExp('_!!_'),_tmpList=_tmpLineObj.rQrcStr.trim().split(_reg),_tmpLineTags=_tmpLineObj.lineFlags;for(i=1,_len=_tmpList.length;i<_len;i++){_cache=_tmpList[i];_reg=new RegExp('[\\[|\\]]','g');var _tmpTag=_tmpLineTags[i-1].replace(_reg,''),_pointPos=0;if(_tmpTag.indexOf('al:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.album=_this.qrcJson.al=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('ar:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.artist=_this.qrcJson.ar=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('ti:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.songTitle=_this.qrcJson.ti=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('by:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.byBody=_this.qrcJson.by=_tmpTag.substring(_pointPos+1);}else if(_tmpTag.indexOf('offset:')!=-1){_pointPos=_tmpTag.indexOf(':');_this.offset=_this.qrcJson.offset=_tmpTag.substring(_pointPos+1);}else{var _tmpTimes=_tmpTag.split(','),_tmpObj=_this.getWordFlag(_cache.replace('``````````',''));_this.qrcJson.lines.push({timeTag:{startTime:parseInt(_tmpTimes[0].trim(),10)-_this.offset,timeLen:parseInt(_tmpTimes[1].trim(),10)},context:(!!_tmpObj)?_tmpObj.rLineStr:'',wordsItem:(!!_tmpObj)?_tmpObj.wordFlags:[]});}}};_this.printQrcLines=function(){var _json=_this.qrcJson;if(!!_json){var _lines=_json.lines,_len=_lines.length,i=0,_html=[];for(;i<_len;i++){var _h5=(!!ua.safari||!!ua.chrome||!!ua.isiPad||!!ua.isiPhone);if(!!_h5){_html.push('<p id="line_'+i+'">'+_lines[i].context+'</p>');}else{_html.push('<p id="line_'+i+'"><span>'+_lines[i].context+'</span></p>');}}
return _html.join('');}
return'';};_this.getLineFlag=function(qrcStr){qrcStr=qrcStr||_this.qrcData;var _tmpStr=qrcStr,reg=new RegExp("\\[[a-z|0-9]+\\s*[:|,]\\s*[^\\]]*\\]","gi"),lineFlags=[],rtnObj={},rQrcStr='';lineFlags=_tmpStr.match(reg);rQrcStr=_tmpStr.replace(reg,'``````````_!!_');return{lineFlags:lineFlags,rQrcStr:rQrcStr};};_this.getWordFlag=function(lineTxt){lineTxt=lineTxt.trim()||'';if(''==lineTxt){return null;}
var _tmpLineTxt=lineTxt,reg=new RegExp('\\([\-0-9]+,\\s*[\-0-9]+\\)','g'),wordFlags=[],_wordFlag={},words=[],rtnObj={},rtnWordFlags=[],rtnLineStr='';wordFlags=_tmpLineTxt.match(reg);words=_tmpLineTxt.replace(reg,'_!!_').split('_!!_');rtnLineStr=_tmpLineTxt.replace(reg,'');if(wordFlags==null){rtnObj={wordFlags:[],rLineStr:rtnLineStr};return rtnObj;}
for(var i=0,_len=wordFlags.length;i<_len;i++){var _tmp=wordFlags[i],wordTimes=_tmp.replace(new RegExp('[\\(|\\)]','g'),'').split(',');_wordFlag={word:words[i],startTime:(parseInt(wordTimes[0].trim(),10)-_this.offset),timeLen:parseInt(wordTimes[1].trim(),10)};rtnWordFlags.push(_wordFlag);}
rtnObj={wordFlags:rtnWordFlags,rLineStr:rtnLineStr};return rtnObj;};_this.clearQrcInfo=function(){_this.haveqrc=false;_this.qrcJson={ar:'',ti:'',al:'',by:'',offset:'',lines:[]};_this.qrcLineIndex=0;_this.qrcData='';_this.artist='';_this.songTitle='';_this.album='';_this.byBody='';_this.offset=0;_this.reqFlag=false;_this.stopAnimFrame();};_this.clearQrcItem=function(){_this.lineItem={timeTag:{startTime:0,timeLen:0},context:'',wordsItem:[]};_this.wordItem={word:'',startTime:0,timeLen:0};};_this.getQrcLineItemByPlayTime=function(playTime){playTime=playTime||0;var _curLineIndex=_this.qrcLineIndex,_curLineItem=_this.qrcJson.lines[_curLineIndex],i=0,_len=_this.qrcJson.lines.length-1,_line={};_this.clearQrcItem();for(;i<_len;i++){_line=_this.qrcJson.lines[i];var _start=_line.timeTag.startTime,_delay=_line.timeTag.timeLen,_dx=playTime-_start;if(_dx>=0&&_dx<=_delay){_this.lineItem=_line;_this.qrcLineIndex=i;return true;}}
_line=_this.qrcJson.lines[_len];_start=_line.timeTag.startTime;_delay=_line.timeTag.timeLen;_dx=playTime-_start;if(_dx>=0){_this.lineItem=_line;_this.qrcLineIndex=_len;return true;}
return false;};_this.getHighlightWords=function(playTime,lineIndex){playTime=playTime||0;lineIndex=lineIndex||_this.qrcLineIndex;if(playTime<_this.qrcJson.lines[0].timeTag.startTime){return'';}
var _line=_this.qrcJson.lines[lineIndex],_wordsItem=_line.wordsItem,_start=_line.timeTag.startTime,i=0,_len=_wordsItem.length,_delay=0,_word={},_highlightWords=[];for(;i<_len;i++){_word=_wordsItem[i];_delay+=parseInt(_word.timeLen,10);if(_delay>playTime-_start){_highlightWords.push(_word.word);return _highlightWords.join('');}
_highlightWords.push(_word.word);}};_this.scrollLine=function(elem){elem=(typeof elem=='string')?$D.get(elem):elem;var max=parseInt(elem.scrollHeight-72),_top=elem.scrollTop,_line_height=(!!$D.get('line_'+g_qrcHandlerChn.qrcLineIndex))?$D.get('line_'+g_qrcHandlerChn.qrcLineIndex).offsetHeight:24,stop=false,_idx=g_qrcHandlerChn.qrcLineIndex||0,heights=0,_times=parseInt(_line_height/6,10),_off=_line_height%6;while(_idx-->0){var _h=(!!$D.get('line_'+_idx))?$D.get('line_'+_idx).offsetHeight:24;heights+=_h;}
stop=(_top==heights);if(!stop){if(heights-_top>=_line_height*2){elem.scrollTop=heights;}else{var _diff=heights-_top;if(_diff>_line_height){_diff-=_line_height;}
var _t=(_diff>=_times)?_times:_off;elem.scrollTop=_top+_t;}}
g_qrcHandlerChn.startAnimFrame(elem);};_this.aniFrame=null;_this.qrcAnimFrame=function(cb,delay){return window.requestTimeout(cb,delay);};_this.startAnimFrame=function(elem){g_qrcHandlerChn.aniFrame=g_qrcHandlerChn.qrcAnimFrame(function(){g_qrcHandlerChn.scrollLine(elem);},delay);};_this.stopAnimFrame=function(){if(g_qrcHandlerChn.aniFrame!=null){window.cancelRequestAnimFrame(g_qrcHandlerChn.aniFrame);}
g_qrcHandlerChn.aniFrame=null;};_this.restartAnimFrame=function(elem){g_qrcHandlerChn.stopAnimFrame();g_qrcHandlerChn.startAnimFrame(elem);};}})();var g_qrcHandlerChn=new MUSIC.channel.qrcHandler();var delay=1000/60*12;(function(){window.requestAnimFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback,element){window.setTimeout(callback,1000/60);};})();window.cancelRequestAnimFrame=function(handle){window.cancelAnimationFrame?window.cancelAnimationFrame(handle.value):window.webkitCancelRequestAnimationFrame?window.webkitCancelRequestAnimationFrame(handle.value):window.mozCancelRequestAnimationFrame?window.mozCancelRequestAnimationFrame(handle.value):window.oCancelRequestAnimationFrame?window.oCancelRequestAnimationFrame(handle.value):window.msCancelRequestAnimationFrame?window.msCancelRequestAnimationFrame(handle.value):window.clearTimeout(handle);};window.requestTimeout=function(cb,delay){if(!window.requestAnimationFrame&&!window.webkitRequestAnimationFrame&&!window.mozRequestAnimationFrame&&!window.oRequestAnimationFrame&&!window.msRequestAnimationFrame){return window.setTimeout(cb,delay);}
var start=(new Date()).getTime(),handle=new Object();function loop(){var current=(new Date()).getTime(),delta=current-start;delta>=delay?cb.call():handle.value=window.requestAnimFrame(loop);};handle.value=window.requestAnimFrame(loop);return handle;};})();MUSIC.module.coder=(function(){var _this=this;var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(input){var output="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;input=Base64._utf8_encode(input);while(i<input.length){chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
output=output+
Base64._keyStr.charAt(enc1)+Base64._keyStr.charAt(enc2)+
Base64._keyStr.charAt(enc3)+Base64._keyStr.charAt(enc4);}
return output;},decode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=Base64._keyStr.indexOf(input.charAt(i++));enc2=Base64._keyStr.indexOf(input.charAt(i++));enc3=Base64._keyStr.indexOf(input.charAt(i++));enc4=Base64._keyStr.indexOf(input.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;output=output+String.fromCharCode(chr1);if(enc3!=64){output=output+String.fromCharCode(chr2);}
if(enc4!=64){output=output+String.fromCharCode(chr3);}}
output=Base64._utf8_decode(output);return output;},_utf8_encode:function(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128){utftext+=String.fromCharCode(c);}else if((c>127)&&(c<2048)){utftext+=String.fromCharCode((c>>6)|192);utftext+=String.fromCharCode((c&63)|128);}else{utftext+=String.fromCharCode((c>>12)|224);utftext+=String.fromCharCode(((c>>6)&63)|128);utftext+=String.fromCharCode((c&63)|128);}}
return utftext;},_utf8_decode:function(utftext){var string="";var i=0;var c=c1=c2=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string+=String.fromCharCode(c);i++;}else if((c>191)&&(c<224)){c2=utftext.charCodeAt(i+1);string+=String.fromCharCode(((c&31)<<6)|(c2&63));i+=2;}else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string+=String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63));i+=3;}}
return string;}};return{Base64:Base64};})();var g_coder=MUSIC.module.coder;/*  |xGv00|c7aac837e6e03a0ce84cdc517e2d67ad */